spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.3.6:5432/qing
    hikari:
      username: root
      password: admin123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mail:
    host: smtp.qq.com
    username: your_mail_count
    password: your_mail_token
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: false
qing:
  openAopLog: true
  api:
    doc-disabled: false
  index-size: 26
  security:
    jwt:
      secret: 123123
      header: jwt
      expiration: 100000
    authing:
      appId: 6432d5c9e0502f0bb45319bf
      appSecret: a599ddfc87b4478596b31a17e46d2360
      appHost: https://stanic.authing.cn/6432d5c9e0502f0bb45319bf
      redirectUrl: http://localhost:8080/api/auth2/authorization
      authLoginUrlPrefix: /api/auth2/authorization
      auto-sign-up: true
      login-page: http://localhost:5173/#/login/Authing
  mp:
    # 测试账号
    appId: wx9e955703886af7c9
    secret: 9d8cbf48467d38006f50f13d499f5abc
    token: 123123
    aes-key: ZcipcxwIwYh0WFFdBPZXlrxzNVmTWPq4OuVh4RzHGh6
