/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.user.third.updater;

import cn.chenyunlong.qing.domain.user.third.ThirdUser;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;

import lombok.Data;

@Schema
@Data
public class ThirdUserUpdater {
    @Schema(
            title = "UserId",
            description = "userId"
    )
    private Long userId;

    @Schema(
            title = "Uid",
            description = "uid"
    )
    private String uid;

    @Schema(
            title = "AppType",
            description = "appType"
    )
    private String appType;

    @Schema(
            title = "AccessToken",
            description = "accessToken"
    )
    private String accessToken;

    @Schema(
            title = "AccessExpire",
            description = "accessExpire"
    )
    private Integer accessExpire;

    private Long id;

    public void updateThirdUser(ThirdUser param) {
        Optional.ofNullable(getUserId()).ifPresent(v -> param.setUserId(v));
        Optional.ofNullable(getUid()).ifPresent(v -> param.setUid(v));
        Optional.ofNullable(getAppType()).ifPresent(v -> param.setAppType(v));
        Optional.ofNullable(getAccessToken()).ifPresent(v -> param.setAccessToken(v));
        Optional.ofNullable(getAccessExpire()).ifPresent(v -> param.setAccessExpire(v));
    }
}
