// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.lifecycle.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.anime.lifecycle.creator.AnimeLifeCycleCreator;
import cn.chenyunlong.qing.domain.anime.lifecycle.query.AnimeLifeCycleQuery;
import cn.chenyunlong.qing.domain.anime.lifecycle.updater.AnimeLifeCycleUpdater;
import cn.chenyunlong.qing.domain.anime.lifecycle.vo.AnimeLifeCycleVO;

import java.lang.Long;

import org.springframework.data.domain.Page;

public interface IAnimeLifeCycleService {
    /**
     * create
     */
    Long createAnimeLifeCycle(AnimeLifeCycleCreator creator);

    /**
     * update
     */
    void updateAnimeLifeCycle(AnimeLifeCycleUpdater updater);

    /**
     * valid
     */
    void validAnimeLifeCycle(Long id);

    /**
     * invalid
     */
    void invalidAnimeLifeCycle(Long id);

    /**
     * findById
     */
    AnimeLifeCycleVO findById(Long id);

    /**
     * findByPage
     */
    Page<AnimeLifeCycleVO> findByPage(PageRequestWrapper<AnimeLifeCycleQuery> query);
}
