// ---Auto Generated by Qing-Generator --

package cn.chenyunlong.qing.domain.entity.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.entity.creator.EntityCreator;
import cn.chenyunlong.qing.domain.entity.query.EntityQuery;
import cn.chenyunlong.qing.domain.entity.updater.EntityUpdater;
import cn.chenyunlong.qing.domain.entity.vo.EntityVO;
import org.springframework.data.domain.Page;

public interface IEntityService {
    /**
     * create
     */
    Long createEntity(EntityCreator creator);

    /**
     * update
     */
    void updateEntity(EntityUpdater updater);

    /**
     * valid
     */
    void validEntity(Long id);

    /**
     * invalid
     */
    void invalidEntity(Long id);

    /**
     * findById
     */
    EntityVO findById(Long id);

    /**
     * findByPage
     */
    Page<EntityVO> findByPage(PageRequestWrapper<EntityQuery> query);

    /**
     * 更新实体类的点赞数量
     *
     * @param entityId 实体ID
     */
    void updateZanCount(Long entityId);
}
