server:
  port: 8761
spring:
  application:
    name: qing-eureka-server
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
