// Auto Generated by Qing Code Generator
// Do not modify this file manually
// Generated at: 2025-08-24T16:06:50.741764400
package cn.chenyunlong.codegen.example.domain.dto.query;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * Order查询条件对象
 *
 * @author 代码生成器
 * @since 2025-08-24 16:06:50
 */
@Schema(
        name = "OrderQuery",
        description = "Order查询条件对象"
)
@Data
public class OrderQuery {
}
