// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.file.creator;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class UploadFileCreator {
    @Schema(
            title = "FileId",
            description = "fileId"
    )
    private Long fileId;

    @Schema(
            title = "FileName",
            description = "fileName"
    )
    private String fileName;

    @Schema(
            title = "MimeType",
            description = "mimeType"
    )
    private String mimeType;

    @Schema(
            title = "Url",
            description = "url"
    )
    private String url;

    @Schema(
            title = "FileSize",
            description = "fileSize"
    )
    private Long fileSize;
}
