// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.user.third.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.user.third.ThirdUser;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AccessLevel;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Schema
@Data
@EqualsAndHashCode(
        callSuper = true
)
@NoArgsConstructor(
        access = AccessLevel.PROTECTED
)
public class ThirdUserVO extends AbstractBaseJpaVO {
    @Schema(
            title = "UserId",
            description = "userId"
    )
    private Long userId;

    @Schema(
            title = "Uid",
            description = "uid"
    )
    private String uid;

    @Schema(
            title = "AppType",
            description = "appType"
    )
    private String appType;

    @Schema(
            title = "AccessToken",
            description = "accessToken"
    )
    private String accessToken;

    @Schema(
            title = "AccessExpire",
            description = "accessExpire"
    )
    private Integer accessExpire;

    public ThirdUserVO(ThirdUser source) {
        super();
        this.setUserId(source.getUserId());
        this.setUid(source.getUid());
        this.setAppType(source.getAppType());
        this.setAccessToken(source.getAccessToken());
        this.setAccessExpire(source.getAccessExpire());
    }
}
