// Auto Generated by Qing Code Generator
// Do not modify this file manually
// Generated at: 2025-08-22T03:43:26.952556900

package cn.chenyunlong.codegen.example.domain.service;

import cn.chenyunlong.codegen.example.domain.dto.creator.OrderCreator;
import cn.chenyunlong.codegen.example.domain.dto.query.OrderQuery;
import cn.chenyunlong.codegen.example.domain.dto.updater.OrderUpdater;
import cn.chenyunlong.codegen.example.domain.dto.vo.OrderVO;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.common.AggregateId;
import org.springframework.data.domain.Page;

public interface IOrderService {
    /**
     * create
     */
    Long createOrder(OrderCreator creator);

    /**
     * update
     */
    void updateOrder(OrderUpdater updater);

    /**
     * valid
     */
    void validOrder(AggregateId id);

    /**
     * invalid
     */
    void invalidOrder(AggregateId id);

    /**
     * findById
     */
    OrderVO findById(AggregateId id);

    /**
     * findByPage
     */
    Page<OrderVO> findByPage(PageRequestWrapper<OrderQuery> query);
}
