/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.job.log.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Date;

@Schema
@Data
@EqualsAndHashCode(
        callSuper = true
)
public class SysJobLogResponse extends AbstractJpaResponse {
    @Schema(
            title = "jobLogId",
            description = "jobLogId"
    )
    private Long jobLogId;

    @Schema(
            title = "jobName",
            description = "jobName"
    )
    private String jobName;

    @Schema(
            title = "jobGroup",
            description = "jobGroup"
    )
    private String jobGroup;

    @Schema(
            title = "invokeTarget",
            description = "invokeTarget"
    )
    private String invokeTarget;

    @Schema(
            title = "jobMessage",
            description = "jobMessage"
    )
    private String jobMessage;

    @Schema(
            title = "status",
            description = "status"
    )
    private String status;

    @Schema(
            title = "exceptionInfo",
            description = "exceptionInfo"
    )
    private String exceptionInfo;

    @Schema(
            title = "startTime",
            description = "startTime"
    )
    private Date startTime;

    @Schema(
            title = "endTime",
            description = "endTime"
    )
    private Date endTime;
}
