server:
  port: 8086

spring:
  application:
    name: qing-service-leave
  datasource:
    driver-class-name: org.postgresql.Driver
    username: qing-leave
    password: 123456
    url: jdbc:postgresql://192.168.3.112:5432/qing-leave
  rabbitmq:
    host: 192.168.3.112
    username: rabbitmq
    password: 123456
  data:
    redis:
      host: 192.168.3.112
      database: 0
      password: 123456
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Administrator
    webapp:
      application-path: /camunda
    database:
      schema-update: false
    history-level: full
    generic-properties:
      properties:
        enforceHistoryTimeToLive: false
    auto-deployment-enabled: false
    history-level-default: full
    filter:
      create: All tasks
    authorization:
      enabled: true
logging:
  level:
    root: info
