// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.file.service;

import cn.chenyunlong.common.model.JsonObject;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.common.model.PageResult;
import cn.chenyunlong.qing.domain.file.request.UploadFileCreateRequest;
import cn.chenyunlong.qing.domain.file.request.UploadFileQueryRequest;
import cn.chenyunlong.qing.domain.file.request.UploadFileUpdateRequest;
import cn.chenyunlong.qing.domain.file.response.UploadFileResponse;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

@FeignClient(
        value = "xxxSrv",
        contextId = "uploadFileClient",
        path = "uploadFile/v1"
)
public interface UploadFileFeignService {
    /**
     * createRequest
     */
    @PostMapping("createUploadFile")
    JsonObject<Long> createUploadFile(@RequestBody UploadFileCreateRequest request);

    /**
     * update request
     */
    @PostMapping("updateUploadFile")
    JsonObject<String> updateUploadFile(@RequestBody UploadFileUpdateRequest request);

    /**
     * valid
     */
    @PostMapping("valid/{id}")
    JsonObject<String> validUploadFile(@PathVariable("id") Long id);

    /**
     * invalid
     */
    @PostMapping("invalid/{id}")
    JsonObject<String> invalidUploadFile(@PathVariable("id") Long id);

    /**
     * findById
     */
    @GetMapping("findById/{id}")
    JsonObject<UploadFileResponse> findById(@PathVariable("id") Long id);

    /**
     * findByPage request
     */
    @PostMapping("findByPage")
    JsonObject<PageResult<UploadFileResponse>> findByPage(
            @RequestBody PageRequestWrapper<UploadFileQueryRequest> request);
}
