// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.system.job.log.service;

import cn.chenyunlong.common.model.JsonObject;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.common.model.PageResult;
import cn.chenyunlong.qing.domain.system.job.log.request.SysJobLogCreateRequest;
import cn.chenyunlong.qing.domain.system.job.log.request.SysJobLogQueryRequest;
import cn.chenyunlong.qing.domain.system.job.log.request.SysJobLogUpdateRequest;
import cn.chenyunlong.qing.domain.system.job.log.response.SysJobLogResponse;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

@FeignClient(
        value = "xxxSrv",
        contextId = "sysJobLogClient",
        path = "sysJobLog/v1"
)
public interface SysJobLogFeignService {
    /**
     * createRequest
     */
    @PostMapping("createSysJobLog")
    JsonObject<Long> createSysJobLog(@RequestBody SysJobLogCreateRequest request);

    /**
     * update request
     */
    @PostMapping("updateSysJobLog")
    JsonObject<String> updateSysJobLog(@RequestBody SysJobLogUpdateRequest request);

    /**
     * valid
     */
    @PostMapping("valid/{id}")
    JsonObject<String> validSysJobLog(@PathVariable("id") Long id);

    /**
     * invalid
     */
    @PostMapping("invalid/{id}")
    JsonObject<String> invalidSysJobLog(@PathVariable("id") Long id);

    /**
     * findById
     */
    @GetMapping("findById/{id}")
    JsonObject<SysJobLogResponse> findById(@PathVariable("id") Long id);

    /**
     * findByPage request
     */
    @PostMapping("findByPage")
    JsonObject<PageResult<SysJobLogResponse>> findByPage(
            @RequestBody PageRequestWrapper<SysJobLogQueryRequest> request);
}
