// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.playlist.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.anime.playlist.Playlist;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Long;
import java.lang.String;

import lombok.AccessLevel;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Schema
@Data
@EqualsAndHashCode(
        callSuper = true
)
@NoArgsConstructor(
        access = AccessLevel.PROTECTED
)
public class PlaylistVO extends AbstractBaseJpaVO {
    @Schema(
            title = "animeId",
            description = "animeId"
    )
    private Long animeId;

    @Schema(
            title = "name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "description",
            description = "description"
    )
    private String description;

    public PlaylistVO(Playlist source) {
        super();
        this.setAnimeId(source.getAnimeId());
        this.setName(source.getName());
        this.setDescription(source.getDescription());
    }
}
