// ---Auto Generated by Qing-Generator --

package cn.chenyunlong.qing.samples.codegen.domain.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class TestDomainResponse extends AbstractJpaResponse {
    static {
    }

    @Schema(
        title = "username",
        description = "username"
    )
    private String username;

    @Schema(
        title = "password",
        description = "password"
    )
    private String password;
}
