// ---Auto Generated by Qing-Generator --
package cn.chenyunlong.qing.samples.codegen.domain.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.String;

@Schema
public class TestDomainResponse extends AbstractJpaResponse {
    static {
    }

    @Schema(
            title = "username",
            description = "username"
    )
    private String username;

    @Schema(
            title = "password",
            description = "password"
    )
    private String password;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
