// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.sign.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class SignResponse extends AbstractJpaResponse {
    @Schema(
            title = "UserId"
    )
    private Long userId;

    @Schema(
            title = "DateMonth"
    )
    private Long dateMonth;

    @Schema(
            title = "Mask"
    )
    private Integer mask;

    @Schema(
            title = "ContinueSignMonth"
    )
    private Integer continueSignMonth;
}
