/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.sign.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Integer;
import java.lang.Long;

@Schema
public class SignResponse extends AbstractJpaResponse {
    @Schema(
            title = "UserId",
            description = ""
    )
    private Long userId;

    @Schema(
            title = "DateMonth",
            description = ""
    )
    private Long dateMonth;

    @Schema(
            title = "Mask",
            description = ""
    )
    private Integer mask;

    @Schema(
            title = "ContinueSignMonth",
            description = ""
    )
    private Integer continueSignMonth;
}
