// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.sign.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Integer;
import java.lang.Long;

import lombok.Data;

@Schema
@Data
public class SignResponse extends AbstractJpaResponse {
    @Schema(
            title = "userId"
    )
    private Long userId;

    @Schema(
            title = "dateMonth"
    )
    private Long dateMonth;

    @Schema(
            title = "mask"
    )
    private Integer mask;

    @Schema(
            title = "continueSignMonth"
    )
    private Integer continueSignMonth;
}
