// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.config.updater;

import cn.chenyunlong.qing.domain.system.config.SysConfig;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Long;
import java.lang.String;
import java.util.Optional;

import lombok.Data;

@Schema
@Data
public class SysConfigUpdater {
    @Schema(
            title = "configId",
            description = "configId"
    )
    private Long configId;

    @Schema(
            title = "configName",
            description = "configName"
    )
    private String configName;

    @Schema(
            title = "configKey",
            description = "configKey"
    )
    private String configKey;

    @Schema(
            title = "configValue",
            description = "configValue"
    )
    private String configValue;

    @Schema(
            title = "configType",
            description = "configType"
    )
    private String configType;

    @Schema(
            title = "params",
            description = "params"
    )
    private String params;

    private Long id;

    public void updateSysConfig(SysConfig param) {
        Optional.ofNullable(getConfigId()).ifPresent(param::setConfigId);
        Optional.ofNullable(getConfigName()).ifPresent(param::setConfigName);
        Optional.ofNullable(getConfigKey()).ifPresent(param::setConfigKey);
        Optional.ofNullable(getConfigValue()).ifPresent(param::setConfigValue);
        Optional.ofNullable(getConfigType()).ifPresent(param::setConfigType);
        Optional.ofNullable(getParams()).ifPresent(param::setParams);
    }
}
