/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.lifecycle.service.impl;

import cn.chenyunlong.common.constants.CodeEnum;
import cn.chenyunlong.common.exception.BusinessException;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.jpa.support.EntityOperations;
import cn.chenyunlong.qing.domain.anime.lifecycle.AnimeLifeCycle;
import cn.chenyunlong.qing.domain.anime.lifecycle.creator.AnimeLifeCycleCreator;
import cn.chenyunlong.qing.domain.anime.lifecycle.mapper.AnimeLifeCycleMapper;
import cn.chenyunlong.qing.domain.anime.lifecycle.query.AnimeLifeCycleQuery;
import cn.chenyunlong.qing.domain.anime.lifecycle.repository.AnimeLifeCycleRepository;
import cn.chenyunlong.qing.domain.anime.lifecycle.service.IAnimeLifeCycleService;
import cn.chenyunlong.qing.domain.anime.lifecycle.updater.AnimeLifeCycleUpdater;
import cn.chenyunlong.qing.domain.anime.lifecycle.vo.AnimeLifeCycleVO;
import com.querydsl.core.BooleanBuilder;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;
import java.util.stream.Collectors;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class AnimeLifeCycleServiceImpl implements IAnimeLifeCycleService {
    private final AnimeLifeCycleRepository animeLifeCycleRepository;

    /**
     * createImpl
     */
    @Override
    public Long createAnimeLifeCycle(AnimeLifeCycleCreator creator) {
        Optional<AnimeLifeCycle> animeLifeCycle = EntityOperations.doCreate(animeLifeCycleRepository)
                .create(() -> AnimeLifeCycleMapper.INSTANCE.dtoToEntity(creator))
                .update(e -> e.init())
                .execute();
        return animeLifeCycle.isPresent() ? animeLifeCycle.get().getId() : 0;
    }

    /**
     * update
     */
    @Override
    public void updateAnimeLifeCycle(AnimeLifeCycleUpdater updater) {
        EntityOperations.doUpdate(animeLifeCycleRepository)
                .loadById(updater.getId())
                .update(e -> updater.updateAnimeLifeCycle(e))
                .execute();
    }

    /**
     * valid
     */
    @Override
    public void validAnimeLifeCycle(Long id) {
        EntityOperations.doUpdate(animeLifeCycleRepository)
                .loadById(id)
                .update(e -> e.valid())
                .execute();
    }

    /**
     * invalid
     */
    @Override
    public void invalidAnimeLifeCycle(Long id) {
        EntityOperations.doUpdate(animeLifeCycleRepository)
                .loadById(id)
                .update(e -> e.invalid())
                .execute();
    }

    /**
     * findById
     */
    @Override
    public AnimeLifeCycleVO findById(Long id) {
        Optional<AnimeLifeCycle> animeLifeCycle = animeLifeCycleRepository.findById(id);
        return new AnimeLifeCycleVO(animeLifeCycle.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
    }

    /**
     * findByPage
     */
    @Override
    public Page<AnimeLifeCycleVO> findByPage(PageRequestWrapper<AnimeLifeCycleQuery> query) {
        BooleanBuilder booleanBuilder = new BooleanBuilder();
        Page<AnimeLifeCycle> page = animeLifeCycleRepository.findAll(booleanBuilder,
                PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                        Sort.Direction.DESC, "createdAt")));
        return new PageImpl<>(page.getContent()
                .stream().map(AnimeLifeCycleVO::new)
                .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
    }
}
