services:
  postgres_db: # 服务名称
    image: stanic-docker.stanic.xyz/library/postgres:latest # 指定镜像及其版本
    container_name: docker_postgres # 指定容器的名称
    restart: always
    environment:
      POSTGRES_PASSWORD: admin@123456
      #POSTGRES_DB: default
    ports: # 端口映射
      - "5432:5432"
    volumes: # 数据持久化的配置
      - postgres-data:/var/lib/postgresql/data
      - postgres-log:/var/log/postgresql
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes: # 数据卷
  postgres-data:
  postgres-log:
