// Auto Generated by Qing Code Generator
// Do not modify this file manually
// Generated at: 2025-08-22T03:43:26.815323700
package cn.chenyunlong.codegen.example.domain.dto.query;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * Product查询条件对象
 *
 * @author 代码生成器
 * @since 2025-08-22 03:43:26
 */
@Schema(
        name = "ProductQuery",
        description = "Product查询条件对象"
)
@Data
public class ProductQuery {
}
