// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.district.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.district.District;

import java.lang.Long;

public interface DistrictRepository extends BaseRepository<District, Long> {
}
