/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.version.updater;

import cn.chenyunlong.qing.domain.system.version.Version;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.Optional;

@Schema
@Data
public class VersionUpdater {
    @Schema(
            title = "Code"
    )
    private String code;

    @Schema(
            title = "Name"
    )
    private String name;

    @Schema(
            title = "Description"
    )
    private String description;

    private Long id;

    public void updateVersion(Version param) {
        Optional.ofNullable(getCode()).ifPresent(v -> param.setCode(v));
        Optional.ofNullable(getName()).ifPresent(v -> param.setName(v));
        Optional.ofNullable(getDescription()).ifPresent(v -> param.setDescription(v));
    }
}
