// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.version.updater;

import cn.chenyunlong.qing.domain.system.version.Version;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Long;
import java.lang.String;
import java.util.Optional;

import lombok.Data;

@Schema
@Data
public class VersionUpdater {
    @Schema(
            title = "Code"
    )
    private String code;

    @Schema(
            title = "Name"
    )
    private String name;

    @Schema(
            title = "Description"
    )
    private String description;

    private Long id;

    public void updateVersion(Version param) {
        Optional.ofNullable(getCode()).ifPresent(v -> param.setCode(v));
        Optional.ofNullable(getName()).ifPresent(v -> param.setName(v));
        Optional.ofNullable(getDescription()).ifPresent(v -> param.setDescription(v));
    }
}
