// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.comment.mapper;

import cn.chenyunlong.common.mapper.DateMapper;
import cn.chenyunlong.common.mapper.GenericEnumMapper;
import cn.chenyunlong.qing.domain.anime.comment.Comment;
import cn.chenyunlong.qing.domain.anime.comment.creator.CommentCreator;
import cn.chenyunlong.qing.domain.anime.comment.query.CommentQuery;
import cn.chenyunlong.qing.domain.anime.comment.request.CommentCreateRequest;
import cn.chenyunlong.qing.domain.anime.comment.request.CommentQueryRequest;
import cn.chenyunlong.qing.domain.anime.comment.request.CommentUpdateRequest;
import cn.chenyunlong.qing.domain.anime.comment.response.CommentResponse;
import cn.chenyunlong.qing.domain.anime.comment.updater.CommentUpdater;
import cn.chenyunlong.qing.domain.anime.comment.vo.CommentVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
        uses = {
                GenericEnumMapper.class,
                DateMapper.class
        }
)
public interface CommentMapper {
    CommentMapper INSTANCE = Mappers.getMapper(CommentMapper.class);

    Comment dtoToEntity(CommentCreator dto);

    CommentUpdater request2Updater(CommentUpdateRequest request);

    CommentCreator request2Dto(CommentCreateRequest request);

    CommentQuery request2Query(CommentQueryRequest request);

    CommentResponse vo2Response(CommentVO vo);

    default CommentResponse vo2CustomResponse(CommentVO vo) {
        CommentResponse response = vo2Response(vo);
        return response;
    }
}
