// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.comment.service;

import cn.chenyunlong.common.model.JsonObject;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.common.model.PageResult;
import cn.chenyunlong.qing.domain.anime.comment.request.CommentCreateRequest;
import cn.chenyunlong.qing.domain.anime.comment.request.CommentQueryRequest;
import cn.chenyunlong.qing.domain.anime.comment.request.CommentUpdateRequest;
import cn.chenyunlong.qing.domain.anime.comment.response.CommentResponse;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

@FeignClient(
        value = "xxxSrv",
        contextId = "commentClient",
        path = "comment/v1"
)
public interface CommentFeignService {
    /**
     * createRequest
     */
    @PostMapping("createComment")
    JsonObject<Long> createComment(@RequestBody CommentCreateRequest request);

    /**
     * update request
     */
    @PostMapping("updateComment")
    JsonObject<String> updateComment(@RequestBody CommentUpdateRequest request);

    /**
     * valid
     */
    @PostMapping("valid/{id}")
    JsonObject<String> validComment(@PathVariable("id") Long id);

    /**
     * invalid
     */
    @PostMapping("invalid/{id}")
    JsonObject<String> invalidComment(@PathVariable("id") Long id);

    /**
     * findById
     */
    @GetMapping("findById/{id}")
    JsonObject<CommentResponse> findById(@PathVariable("id") Long id);

    /**
     * findByPage request
     */
    @PostMapping("findByPage")
    JsonObject<PageResult<CommentResponse>> findByPage(
            @RequestBody PageRequestWrapper<CommentQueryRequest> request);
}
