// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.comment.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.anime.comment.creator.CommentCreator;
import cn.chenyunlong.qing.domain.anime.comment.query.CommentQuery;
import cn.chenyunlong.qing.domain.anime.comment.updater.CommentUpdater;
import cn.chenyunlong.qing.domain.anime.comment.vo.CommentVO;
import org.springframework.data.domain.Page;

public interface ICommentService {
    /**
     * create
     */
    Long createComment(CommentCreator creator);

    /**
     * update
     */
    void updateComment(CommentUpdater updater);

    /**
     * valid
     */
    void validComment(Long id);

    /**
     * invalid
     */
    void invalidComment(Long id);

    /**
     * findById
     */
    CommentVO findById(Long id);

    /**
     * findByPage
     */
    Page<CommentVO> findByPage(PageRequestWrapper<CommentQuery> query);
}
