// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.lifecycle.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.anime.lifecycle.AnimeLifeCycle;

public interface AnimeLifeCycleRepository extends BaseRepository<AnimeLifeCycle, Long> {
}
