// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.system.job.job.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.system.job.job.creator.SysJobCreator;
import cn.chenyunlong.qing.domain.system.job.job.query.SysJobQuery;
import cn.chenyunlong.qing.domain.system.job.job.updater.SysJobUpdater;
import cn.chenyunlong.qing.domain.system.job.job.vo.SysJobVO;
import org.springframework.data.domain.Page;

public interface ISysJobService {
    /**
     * create
     */
    Long createSysJob(SysJobCreator creator);

    /**
     * update
     */
    void updateSysJob(SysJobUpdater updater);

    /**
     * valid
     */
    void validSysJob(Long id);

    /**
     * invalid
     */
    void invalidSysJob(Long id);

    /**
     * findById
     */
    SysJobVO findById(Long id);

    /**
     * findByPage
     */
    Page<SysJobVO> findByPage(PageRequestWrapper<SysJobQuery> query);
}
