// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.job.job.service;

import cn.chenyunlong.common.model.JsonResult;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.common.model.PageResult;
import cn.chenyunlong.qing.domain.system.job.job.request.SysJobCreateRequest;
import cn.chenyunlong.qing.domain.system.job.job.request.SysJobQueryRequest;
import cn.chenyunlong.qing.domain.system.job.job.request.SysJobUpdateRequest;
import cn.chenyunlong.qing.domain.system.job.job.response.SysJobResponse;

import java.lang.Long;
import java.lang.String;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

@FeignClient(
        value = "xxxSrv",
        contextId = "sysJobClient",
        path = "sysJob/v1"
)
public interface SysJobFeignService {
    /**
     * createRequest
     */
    @PostMapping("createSysJob")
    JsonResult<Long> createSysJob(@RequestBody SysJobCreateRequest request);

    /**
     * update request
     */
    @PostMapping("updateSysJob")
    JsonResult<String> updateSysJob(@RequestBody SysJobUpdateRequest request);

    /**
     * valid
     */
    @PostMapping("valid/{id}")
    JsonResult<String> validSysJob(@PathVariable("id") Long id);

    /**
     * invalid
     */
    @PostMapping("invalid/{id}")
    JsonResult<String> invalidSysJob(@PathVariable("id") Long id);

    /**
     * findById
     */
    @GetMapping("findById/{id}")
    JsonResult<SysJobResponse> findById(@PathVariable("id") Long id);

    /**
     * findByPage request
     */
    @PostMapping("findByPage")
    JsonResult<PageResult<SysJobResponse>> findByPage(
            @RequestBody PageRequestWrapper<SysJobQueryRequest> request);
}
