// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.permission.updater;

import cn.chenyunlong.qing.domain.permission.Permission;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.Optional;

@Schema
@Data
public class PermissionUpdater {
    @Schema(
            title = "Name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "Description",
            description = "description"
    )
    private String description;

    private Long id;

    public void updatePermission(Permission param) {
        Optional.ofNullable(getName()).ifPresent(v -> param.setName(v));
        Optional.ofNullable(getDescription()).ifPresent(v -> param.setDescription(v));
    }
}
