// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.user.third.creator;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class ThirdUserCreator {
    @Schema(
            title = "UserId",
            description = "userId"
    )
    private Long userId;

    @Schema(
            title = "Uid",
            description = "uid"
    )
    private String uid;

    @Schema(
            title = "AppType",
            description = "appType"
    )
    private String appType;

    @Schema(
            title = "AccessToken",
            description = "accessToken"
    )
    private String accessToken;

    @Schema(
            title = "AccessExpire",
            description = "accessExpire"
    )
    private Integer accessExpire;
}
