// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.file.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.file.UploadFile;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Long;
import java.lang.String;

import lombok.AccessLevel;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Schema
@Data
@EqualsAndHashCode(
        callSuper = true
)
@NoArgsConstructor(
        access = AccessLevel.PROTECTED
)
public class UploadFileVO extends AbstractBaseJpaVO {
    @Schema(
            title = "fileId",
            description = "fileId"
    )
    private Long fileId;

    @Schema(
            title = "fileName",
            description = "fileName"
    )
    private String fileName;

    @Schema(
            title = "mimeType",
            description = "mimeType"
    )
    private String mimeType;

    @Schema(
            title = "url",
            description = "url"
    )
    private String url;

    @Schema(
            title = "fileSize",
            description = "fileSize"
    )
    private Long fileSize;

    public UploadFileVO(UploadFile source) {
        super();
        this.setFileId(source.getFileId());
        this.setFileName(source.getFileName());
        this.setMimeType(source.getMimeType());
        this.setUrl(source.getUrl());
        this.setFileSize(source.getFileSize());
    }
}
