// ---Auto Generated by Qing-Generator --
package cn.chenyunlong.qing.domain.attachement.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.attachement.creator.AttachmentCreator;
import cn.chenyunlong.qing.domain.attachement.query.AttachmentQuery;
import cn.chenyunlong.qing.domain.attachement.updater.AttachmentUpdater;
import cn.chenyunlong.qing.domain.attachement.vo.AttachmentVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IAttachmentService {
    /**
     * create
     */
    Long createAttachment(AttachmentCreator creator);

    /**
     * update
     */
    void updateAttachment(AttachmentUpdater updater);

    /**
     * valid
     */
    void validAttachment(Long id);

    /**
     * invalid
     */
    void invalidAttachment(Long id);

    /**
     * findById
     */
    AttachmentVO findById(Long id);

    /**
     * findByPage
     */
    Page<AttachmentVO> findByPage(PageRequestWrapper<AttachmentQuery> query);
}
