/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.sign.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDate;

@Schema
public class SignUpdateRequest implements Request {
    @Schema(
            title = "userId"
    )
    private Long userId;

    @Schema(
            title = "dateMonth"
    )
    private LocalDate dateMonth;

    @Schema(
            title = "mask"
    )
    private Integer mask;

    @Schema(
            title = "continueSignMonth"
    )
    private Integer continueSignMonth;

    private Long id;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public LocalDate getDateMonth() {
        return dateMonth;
    }

    public void setDateMonth(LocalDate dateMonth) {
        this.dateMonth = dateMonth;
    }

    public Integer getMask() {
        return mask;
    }

    public void setMask(Integer mask) {
        this.mask = mask;
    }

    public Integer getContinueSignMonth() {
        return continueSignMonth;
    }

    public void setContinueSignMonth(Integer continueSignMonth) {
        this.continueSignMonth = continueSignMonth;
    }

    public Long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
