// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.sign.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDate;

@Schema
public class SignCreateRequest implements Request {
  @Schema(
          title = "userId"
  )
  private Long userId;

  @Schema(
          title = "dateMonth"
  )
  private LocalDate dateMonth;

  @Schema(
          title = "mask"
  )
  private Integer mask;

  @Schema(
          title = "continueSignMonth"
  )
  private Integer continueSignMonth;

  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public LocalDate getDateMonth() {
    return dateMonth;
  }

  public void setDateMonth(LocalDate dateMonth) {
    this.dateMonth = dateMonth;
  }

  public Integer getMask() {
    return mask;
  }

  public void setMask(Integer mask) {
    this.mask = mask;
  }

  public Integer getContinueSignMonth() {
    return continueSignMonth;
  }

  public void setContinueSignMonth(Integer continueSignMonth) {
    this.continueSignMonth = continueSignMonth;
  }
}
