// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.job.log.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.Date;

@Schema
@Data
public class SysJobLogUpdateRequest implements Request {
    @Schema(
            title = "JobLogId",
            description = "jobLogId"
    )
    private Long jobLogId;

    @Schema(
            title = "JobName",
            description = "jobName"
    )
    private String jobName;

    @Schema(
            title = "JobGroup",
            description = "jobGroup"
    )
    private String jobGroup;

    @Schema(
            title = "InvokeTarget",
            description = "invokeTarget"
    )
    private String invokeTarget;

    @Schema(
            title = "JobMessage",
            description = "jobMessage"
    )
    private String jobMessage;

    @Schema(
            title = "Status",
            description = "status"
    )
    private String status;

    @Schema(
            title = "ExceptionInfo",
            description = "exceptionInfo"
    )
    private String exceptionInfo;

    @Schema(
            title = "StartTime",
            description = "startTime"
    )
    private Date startTime;

    @Schema(
            title = "EndTime",
            description = "endTime"
    )
    private Date endTime;

    private Long id;
}
