// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.playlist.updater;

import cn.chenyunlong.qing.domain.anime.playlist.Playlist;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.Optional;

@Schema
@Data
public class PlaylistUpdater {
    @Schema(
            title = "AnimeId",
            description = "animeId"
    )
    private Long animeId;

    @Schema(
            title = "Name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "Description",
            description = "description"
    )
    private String description;

    private Long id;

    public void updatePlaylist(Playlist param) {
        Optional.ofNullable(getAnimeId()).ifPresent(v -> param.setAnimeId(v));
        Optional.ofNullable(getName()).ifPresent(v -> param.setName(v));
        Optional.ofNullable(getDescription()).ifPresent(v -> param.setDescription(v));
    }
}
