// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.anime.updater;

import cn.chenyunlong.qing.domain.anime.anime.AnimeInfo;
import cn.chenyunlong.qing.domain.anime.anime.PlayStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.time.LocalDate;
import java.util.Optional;

@Schema
@Data
public class AnimeInfoUpdater {
    @Schema(
            title = "Name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "Instruction",
            description = "instruction"
    )
    private String instruction;

    @Schema(
            title = "DistrictId",
            description = "districtId"
    )
    private Long districtId;

    @Schema(
            title = "DistrictName",
            description = "districtName"
    )
    private String districtName;

    @Schema(
            title = "CoverUrl",
            description = "coverUrl"
    )
    private String coverUrl;

    @Schema(
            title = "TypeId",
            description = "typeId"
    )
    private Long typeId;

    @Schema(
            title = "TypeName",
            description = "typeName"
    )
    private String typeName;

    @Schema(
            title = "OriginalName",
            description = "originalName"
    )
    private String originalName;

    @Schema(
            title = "OtherName",
            description = "otherName"
    )
    private String otherName;

    @Schema(
            title = "Author",
            description = "author"
    )
    private String author;

    @Schema(
            title = "Company",
            description = "company"
    )
    private String company;

    @Schema(
            title = "PremiereDate",
            description = "premiereDate"
    )
    private LocalDate premiereDate;

    @Schema(
            title = "PlayStatus",
            description = "playStatus"
    )
    private PlayStatus playStatus;

    @Schema(
            title = "PlotType",
            description = "plotType"
    )
    private String plotType;

    @Schema(
            title = "Tags",
            description = "tags"
    )
    private String tags;

    @Schema(
            title = "OfficialWebsite",
            description = "officialWebsite"
    )
    private String officialWebsite;

    @Schema(
            title = "PlayHeat",
            description = "playHeat"
    )
    private String playHeat;

    @Schema(
            title = "OrderNo",
            description = "orderNo"
    )
    private Integer orderNo;

    private Long id;

    public void updateAnimeInfo(AnimeInfo param) {
        Optional.ofNullable(getName()).ifPresent(v -> param.setName(v));
        Optional.ofNullable(getInstruction()).ifPresent(v -> param.setInstruction(v));
        Optional.ofNullable(getDistrictId()).ifPresent(v -> param.setDistrictId(v));
        Optional.ofNullable(getDistrictName()).ifPresent(v -> param.setDistrictName(v));
        Optional.ofNullable(getCoverUrl()).ifPresent(v -> param.setCoverUrl(v));
        Optional.ofNullable(getTypeId()).ifPresent(v -> param.setTypeId(v));
        Optional.ofNullable(getTypeName()).ifPresent(v -> param.setTypeName(v));
        Optional.ofNullable(getOriginalName()).ifPresent(v -> param.setOriginalName(v));
        Optional.ofNullable(getOtherName()).ifPresent(v -> param.setOtherName(v));
        Optional.ofNullable(getAuthor()).ifPresent(v -> param.setAuthor(v));
        Optional.ofNullable(getCompany()).ifPresent(v -> param.setCompany(v));
        Optional.ofNullable(getPremiereDate()).ifPresent(v -> param.setPremiereDate(v));
        Optional.ofNullable(getPlayStatus()).ifPresent(v -> param.setPlayStatus(v));
        Optional.ofNullable(getPlotType()).ifPresent(v -> param.setPlotType(v));
        Optional.ofNullable(getTags()).ifPresent(v -> param.setTags(v));
        Optional.ofNullable(getOfficialWebsite()).ifPresent(v -> param.setOfficialWebsite(v));
        Optional.ofNullable(getPlayHeat()).ifPresent(v -> param.setPlayHeat(v));
        Optional.ofNullable(getOrderNo()).ifPresent(v -> param.setOrderNo(v));
    }
}
