/*
 * Copyright (c) 2019-2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          https://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator --
package cn.chenyunlong.qing.samples.codegen.domain.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.samples.codegen.domain.creator.TestDomainCreator;
import cn.chenyunlong.qing.samples.codegen.domain.query.TestDomainQuery;
import cn.chenyunlong.qing.samples.codegen.domain.updater.TestDomainUpdater;
import cn.chenyunlong.qing.samples.codegen.domain.vo.TestDomainVO;
import org.springframework.data.domain.Page;

public interface ITestDomainService {
    /**
     * create
     */
    Long createTestDomain(TestDomainCreator creator);

    /**
     * update
     */
    void updateTestDomain(TestDomainUpdater updater);

    /**
     * valid
     */
    void validTestDomain(Long id);

    /**
     * invalid
     */
    void invalidTestDomain(Long id);

    /**
     * findById
     */
    TestDomainVO findById(Long id);

    /**
     * findByPage
     */
    Page<TestDomainVO> findByPage(PageRequestWrapper<TestDomainQuery> query);
}
