// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.comment.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.anime.comment.Comment;

public interface CommentRepository extends BaseRepository<Comment, Long> {
}
