// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.playlist.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.anime.playlist.creator.PlaylistCreator;
import cn.chenyunlong.qing.domain.anime.playlist.query.PlaylistQuery;
import cn.chenyunlong.qing.domain.anime.playlist.updater.PlaylistUpdater;
import cn.chenyunlong.qing.domain.anime.playlist.vo.PlaylistVO;

import java.lang.Long;

import org.springframework.data.domain.Page;

public interface IPlaylistService {
    /**
     * create
     */
    Long createPlaylist(PlaylistCreator creator);

    /**
     * update
     */
    void updatePlaylist(PlaylistUpdater updater);

    /**
     * valid
     */
    void validPlaylist(Long id);

    /**
     * invalid
     */
    void invalidPlaylist(Long id);

    /**
     * findById
     */
    PlaylistVO findById(Long id);

    /**
     * findByPage
     */
    Page<PlaylistVO> findByPage(PageRequestWrapper<PlaylistQuery> query);
}
