/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.playlist.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.anime.playlist.creator.PlaylistCreator;
import cn.chenyunlong.qing.domain.anime.playlist.query.PlaylistQuery;
import cn.chenyunlong.qing.domain.anime.playlist.updater.PlaylistUpdater;
import cn.chenyunlong.qing.domain.anime.playlist.vo.PlaylistVO;
import org.springframework.data.domain.Page;

public interface IPlaylistService {
    /**
     * create
     */
    Long createPlaylist(PlaylistCreator creator);

    /**
     * update
     */
    void updatePlaylist(PlaylistUpdater updater);

    /**
     * valid
     */
    void validPlaylist(Long id);

    /**
     * invalid
     */
    void invalidPlaylist(Long id);

    /**
     * findById
     */
    PlaylistVO findById(Long id);

    /**
     * findByPage
     */
    Page<PlaylistVO> findByPage(PageRequestWrapper<PlaylistQuery> query);
}
