// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.attachment.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.anime.attachment.Attachment;

public interface AttachmentRepository extends BaseRepository<Attachment, Long> {
}
