/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.file.mapper;

import cn.chenyunlong.qing.domain.file.UploadFile;
import cn.chenyunlong.qing.domain.file.creator.UploadFileCreator;
import cn.chenyunlong.qing.domain.file.query.UploadFileQuery;
import cn.chenyunlong.qing.domain.file.request.UploadFileCreateRequest;
import cn.chenyunlong.qing.domain.file.request.UploadFileQueryRequest;
import cn.chenyunlong.qing.domain.file.request.UploadFileUpdateRequest;
import cn.chenyunlong.qing.domain.file.response.UploadFileResponse;
import cn.chenyunlong.qing.domain.file.updater.UploadFileUpdater;
import cn.chenyunlong.qing.domain.file.vo.UploadFileVO;
import cn.hutool.core.bean.BeanUtil;

public interface UploadFileMapper {
  UploadFileMapper INSTANCE = new UploadFileMapper() {};

  default UploadFile dtoToEntity(UploadFileCreator dto) {
    return BeanUtil.copyProperties(dto, UploadFile.class);
  }

  default UploadFileUpdater request2Updater(UploadFileUpdateRequest request) {
    return BeanUtil.copyProperties(request, UploadFileUpdater.class);
  }

  default UploadFileCreator request2Dto(UploadFileCreateRequest request) {
    return BeanUtil.copyProperties(request, UploadFileCreator.class);
  }

  default UploadFileQuery request2Query(UploadFileQueryRequest request) {
    return BeanUtil.copyProperties(request, UploadFileQuery.class);
  }

  default UploadFileResponse vo2Response(UploadFileVO vo) {
    return BeanUtil.copyProperties(vo, UploadFileResponse.class);
  }

  default UploadFileResponse vo2CustomResponse(UploadFileVO vo) {
    return vo2Response(vo);
  }
}
