// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.episode.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class EpisodeResponse extends AbstractJpaResponse {
    @Schema(
            title = "animeId"
    )
    private Long animeId;

    @Schema(
            title = "listId"
    )
    private Long listId;

    @Schema(
            title = "name"
    )
    private String name;

    @Schema(
            title = "status"
    )
    private Integer status;

    @Schema(
            title = "uploaderName"
    )
    private String uploaderName;

    @Schema(
            title = "uploaderId"
    )
    private Long uploaderId;

    @Schema(
            title = "url"
    )
    private String url;

    @Schema(
            title = "orderNo"
    )
    private Integer orderNo;
}
