// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.sign.updater;

import cn.chenyunlong.qing.domain.sign.Sign;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.Optional;

@Schema
@Data
public class SignUpdater {
    @Schema(
            title = "UserId"
    )
    private Long userId;

    @Schema(
            title = "DateMonth"
    )
    private Long dateMonth;

    @Schema(
            title = "Mask"
    )
    private Integer mask;

    @Schema(
            title = "ContinueSignMonth"
    )
    private Integer continueSignMonth;

    private Long id;

    public void updateSign(Sign param) {
        Optional.ofNullable(getUserId()).ifPresent(v -> param.setUserId(v));
        Optional.ofNullable(getDateMonth()).ifPresent(v -> param.setDateMonth(v));
        Optional.ofNullable(getMask()).ifPresent(v -> param.setMask(v));
        Optional.ofNullable(getContinueSignMonth()).ifPresent(v -> param.setContinueSignMonth(v));
    }
}
