---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
  namespace: default
data:
  POSTGRES_DB: "qing"
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "admin123456"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: qing
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: localPath
  capacity:
    storage: 5Gi
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: postgres
  name: postgres-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: postgres
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:16.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres-port
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres-config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - name: tcp-8090
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31432
