/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.attachment.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.anime.attachment.creator.AttachmentCreator;
import cn.chenyunlong.qing.domain.anime.attachment.query.AttachmentQuery;
import cn.chenyunlong.qing.domain.anime.attachment.updater.AttachmentUpdater;
import cn.chenyunlong.qing.domain.anime.attachment.vo.AttachmentVO;
import org.springframework.data.domain.Page;

public interface IAttachmentService {
    /**
     * create
     */
    Long createAttachment(AttachmentCreator creator);

    /**
     * update
     */
    void updateAttachment(AttachmentUpdater updater);

    /**
     * valid
     */
    void validAttachment(Long id);

    /**
     * invalid
     */
    void invalidAttachment(Long id);

    /**
     * findById
     */
    AttachmentVO findById(Long id);

    /**
     * findByPage
     */
    Page<AttachmentVO> findByPage(PageRequestWrapper<AttachmentQuery> query);
}
