// ---Auto Generated by Qing-Generator --
package cn.chenyunlong.qing.domain.anime.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.anime.creator.AnimeCreator;
import cn.chenyunlong.qing.domain.anime.query.AnimeQuery;
import cn.chenyunlong.qing.domain.anime.updater.AnimeUpdater;
import cn.chenyunlong.qing.domain.anime.vo.AnimeVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IAnimeService {
    /**
     * create
     */
    Long createAnime(AnimeCreator creator);

    /**
     * update
     */
    void updateAnime(AnimeUpdater updater);

    /**
     * valid
     */
    void validAnime(Long id);

    /**
     * invalid
     */
    void invalidAnime(Long id);

    /**
     * findById
     */
    AnimeVO findById(Long id);

    /**
     * findByPage
     */
    Page<AnimeVO> findByPage(PageRequestWrapper<AnimeQuery> query);
}
