/*
 * Copyright (c) 2019-2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          https://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.service;

import cn.chenyunlong.qing.domain.anime.AnimeInfo;
import cn.chenyunlong.qing.domain.anime.creator.AnimeInfoCreator;
import cn.chenyunlong.qing.domain.anime.updater.AnimeInfoUpdater;
import cn.chenyunlong.qing.domain.anime.vo.AnimeInfoVO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;

public interface IAnimeInfoService {
    /**
     * create
     */
    Long createAnimeInfo(AnimeInfoCreator creator);

    /**
     * update
     */
    void updateAnimeInfo(AnimeInfoUpdater updater);

    /**
     * valid
     */
    void validAnimeInfo(Long id);

    /**
     * invalid
     */
    void invalidAnimeInfo(Long id);

    /**
     * findById
     */
    AnimeInfoVO findById(Long id);

    /**
     * findByPage
     */
    Page<AnimeInfoVO> findByPage(AnimeInfo query, PageRequest pageRequest);
}
