// ---Auto Generated by Qing-Generator --

package cn.chenyunlong.qing.domain.type.service;

import cn.chenyunlong.common.model.JsonResult;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.common.model.PageResult;
import cn.chenyunlong.qing.domain.type.request.TypeCreateRequest;
import cn.chenyunlong.qing.domain.type.request.TypeQueryRequest;
import cn.chenyunlong.qing.domain.type.request.TypeUpdateRequest;
import cn.chenyunlong.qing.domain.type.response.TypeResponse;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

@FeignClient(
    value = "stanic",
    contextId = "typeClient",
    path = "type/v1"
)
public interface TypeFeignService {
    /**
     * createRequest
     */
    @PostMapping("createType")
    JsonResult<Long> createType(@RequestBody TypeCreateRequest request);

    /**
     * update request
     */
    @PostMapping("updateType")
    JsonResult<String> updateType(@RequestBody TypeUpdateRequest request);

    /**
     * valid
     */
    @PostMapping("valid/{id}")
    JsonResult<String> validType(@PathVariable("id") Long id);

    /**
     * invalid
     */
    @PostMapping("invalid/{id}")
    JsonResult<String> invalidType(@PathVariable("id") Long id);

    /**
     * findById
     */
    @GetMapping("findById/{id}")
    JsonResult<TypeResponse> findById(@PathVariable("id") Long id);

    /**
     * findByPage request
     */
    @PostMapping("findByPage")
    JsonResult<PageResult<TypeResponse>> findByPage(
        @RequestBody PageRequestWrapper<TypeQueryRequest> request);
}
