// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.job.log.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.system.job.log.SysJobLog;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.Date;

@Schema
@Data
public class SysJobLogVO extends AbstractBaseJpaVO {
    @Schema(
            title = "JobLogId",
            description = "jobLogId"
    )
    private Long jobLogId;

    @Schema(
            title = "JobName",
            description = "jobName"
    )
    private String jobName;

    @Schema(
            title = "JobGroup",
            description = "jobGroup"
    )
    private String jobGroup;

    @Schema(
            title = "InvokeTarget",
            description = "invokeTarget"
    )
    private String invokeTarget;

    @Schema(
            title = "JobMessage",
            description = "jobMessage"
    )
    private String jobMessage;

    @Schema(
            title = "Status",
            description = "status"
    )
    private String status;

    @Schema(
            title = "ExceptionInfo",
            description = "exceptionInfo"
    )
    private String exceptionInfo;

    @Schema(
            title = "StartTime",
            description = "startTime"
    )
    private Date startTime;

    @Schema(
            title = "EndTime",
            description = "endTime"
    )
    private Date endTime;

    protected SysJobLogVO() {
    }

    public SysJobLogVO(SysJobLog source) {
        super();
        this.setJobLogId(source.getJobLogId());
        this.setJobName(source.getJobName());
        this.setJobGroup(source.getJobGroup());
        this.setInvokeTarget(source.getInvokeTarget());
        this.setJobMessage(source.getJobMessage());
        this.setStatus(source.getStatus());
        this.setExceptionInfo(source.getExceptionInfo());
        this.setStartTime(source.getStartTime());
        this.setEndTime(source.getEndTime());
    }
}
