/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.anime.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import cn.chenyunlong.qing.domain.anime.anime.PlayStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDate;

@Schema
@Data
@EqualsAndHashCode(
        callSuper = true
)
public class AnimeInfoResponse extends AbstractJpaResponse {
    @Schema(
            title = "name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "instruction",
            description = "instruction"
    )
    private String instruction;

    @Schema(
            title = "districtId",
            description = "districtId"
    )
    private Long districtId;

    @Schema(
            title = "districtName",
            description = "districtName"
    )
    private String districtName;

    @Schema(
            title = "coverUrl",
            description = "coverUrl"
    )
    private String coverUrl;

    @Schema(
            title = "typeId",
            description = "typeId"
    )
    private Long typeId;

    @Schema(
            title = "typeName",
            description = "typeName"
    )
    private String typeName;

    @Schema(
            title = "originalName",
            description = "originalName"
    )
    private String originalName;

    @Schema(
            title = "otherName",
            description = "otherName"
    )
    private String otherName;

    @Schema(
            title = "author",
            description = "author"
    )
    private String author;

    @Schema(
            title = "company",
            description = "company"
    )
    private String company;

    @Schema(
            title = "premiereDate",
            description = "premiereDate"
    )
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private LocalDate premiereDate;

    @Schema(
            title = "playStatus",
            description = "playStatus"
    )
    private PlayStatus playStatus;

    @Schema(
            title = "plotType",
            description = "plotType"
    )
    private String plotType;

    @Schema(
            title = "tags",
            description = "tags"
    )
    private String tags;

    @Schema(
            title = "officialWebsite",
            description = "officialWebsite"
    )
    private String officialWebsite;

    @Schema(
            title = "playHeat",
            description = "playHeat"
    )
    private String playHeat;

    @Schema(
            title = "orderNo",
            description = "orderNo"
    )
    private Integer orderNo;
}
