// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.tag.query;

import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.String;

import lombok.Data;

@Schema
@Data
public class AnimeTagQuery {
    @Schema(
            title = "name",
            description = "name"
    )
    private String name;
}
