/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.tag.mapper;

import cn.chenyunlong.qing.domain.anime.tag.AnimeTag;
import cn.chenyunlong.qing.domain.anime.tag.creator.AnimeTagCreator;
import cn.chenyunlong.qing.domain.anime.tag.query.AnimeTagQuery;
import cn.chenyunlong.qing.domain.anime.tag.request.AnimeTagCreateRequest;
import cn.chenyunlong.qing.domain.anime.tag.request.AnimeTagQueryRequest;
import cn.chenyunlong.qing.domain.anime.tag.request.AnimeTagUpdateRequest;
import cn.chenyunlong.qing.domain.anime.tag.response.AnimeTagResponse;
import cn.chenyunlong.qing.domain.anime.tag.updater.AnimeTagUpdater;
import cn.chenyunlong.qing.domain.anime.tag.vo.AnimeTagVO;
import cn.hutool.core.bean.BeanUtil;

public interface AnimeTagMapper {
    AnimeTagMapper INSTANCE = new AnimeTagMapper() {};

    default AnimeTag dtoToEntity(AnimeTagCreator dto) {
        return BeanUtil.copyProperties(dto, AnimeTag.class);
    }

    default AnimeTagUpdater request2Updater(AnimeTagUpdateRequest request) {
        return BeanUtil.copyProperties(request, AnimeTagUpdater.class);
    }

    default AnimeTagCreator request2Dto(AnimeTagCreateRequest request) {
        return BeanUtil.copyProperties(request, AnimeTagCreator.class);
    }

    default AnimeTagQuery request2Query(AnimeTagQueryRequest request) {
        return BeanUtil.copyProperties(request, AnimeTagQuery.class);
    }

    default AnimeTagResponse vo2Response(AnimeTagVO vo) {
        return BeanUtil.copyProperties(vo, AnimeTagResponse.class);
    }

    default AnimeTagResponse vo2CustomResponse(AnimeTagVO vo) {
        return vo2Response(vo);
    }
}
