// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.episode.creator;

import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Integer;
import java.lang.Long;
import java.lang.String;

import lombok.Data;

@Schema
@Data
public class EpisodeCreator {
    @Schema(
            title = "animeId",
            description = "animeId"
    )
    private Long animeId;

    @Schema(
            title = "listId",
            description = "listId"
    )
    private Long listId;

    @Schema(
            title = "name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "status",
            description = "status"
    )
    private Integer status;

    @Schema(
            title = "uploaderName",
            description = "uploaderName"
    )
    private String uploaderName;

    @Schema(
            title = "uploaderId",
            description = "uploaderId"
    )
    private Long uploaderId;

    @Schema(
            title = "url",
            description = "url"
    )
    private String url;

    @Schema(
            title = "orderNo",
            description = "orderNo"
    )
    private Integer orderNo;
}
