#!/bin/bash

### This script is called before the user installs the application.
# 获取用户在向导中的选择
ADMIN_USERNAME="$wizard_admin_username"
ADMIN_PASSWORD="$wizard_admin_password"
DATABASE_TYPE="$wizard_database_type"
APP_PORT="$wizard_app_port"

echo "正在卸载服务！"

echo "管理员用户名: $ADMIN_USERNAME"
echo "数据库类型: $DATABASE_TYPE"
echo "应用端口: $APP_PORT"


exit 0
