/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.activity.service;

import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.qing.domain.activity.creator.ActivityCreator;
import cn.chenyunlong.qing.domain.activity.query.ActivityQuery;
import cn.chenyunlong.qing.domain.activity.updater.ActivityUpdater;
import cn.chenyunlong.qing.domain.activity.vo.ActivityVO;
import org.springframework.data.domain.Page;

public interface IActivityService {
    /**
     * create
     */
    Long createActivity(ActivityCreator creator);

    /**
     * update
     */
    void updateActivity(ActivityUpdater updater);

    /**
     * valid
     */
    void validActivity(Long id);

    /**
     * invalid
     */
    void invalidActivity(Long id);

    /**
     * findById
     */
    ActivityVO findById(Long id);

    /**
     * findByPage
     */
    Page<ActivityVO> findByPage(PageRequestWrapper<ActivityQuery> query);
}
