// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.system.config.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class SysConfigCreateRequest implements Request {
    @Schema(
            title = "configId"
    )
    private Long configId;

    @Schema(
            title = "configName"
    )
    private String configName;

    @Schema(
            title = "configKey"
    )
    private String configKey;

    @Schema(
            title = "configValue"
    )
    private String configValue;

    @Schema(
            title = "configType"
    )
    private String configType;

    @Schema(
            title = "params"
    )
    private String params;

    public Long getConfigId() {
        return configId;
    }

    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    public String getConfigName() {
        return configName;
    }

    public void setConfigName(String configName) {
        this.configName = configName;
    }

    public String getConfigKey() {
        return configKey;
    }

    public void setConfigKey(String configKey) {
        this.configKey = configKey;
    }

    public String getConfigValue() {
        return configValue;
    }

    public void setConfigValue(String configValue) {
        this.configValue = configValue;
    }

    public String getConfigType() {
        return configType;
    }

    public void setConfigType(String configType) {
        this.configType = configType;
    }

    public String getParams() {
        return params;
    }

    public void setParams(String params) {
        this.params = params;
    }
}
