// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.tag.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema
public class AnimeTagQueryRequest implements Request {
    @Schema(
            title = "name"
    )
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
