// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.tag.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.String;

import lombok.Data;

@Schema
@Data
public class AnimeTagQueryRequest implements Request {
    @Schema(
            title = "name",
            description = "name"
    )
    private String name;
}
