@startuml

!include ./eventstorming/single.puml

scale 1.5

Person("管理员")[
管理员
]

Person("用户")[
用户
]

DomainEvent("动漫已创建") [
动漫已创建
--字段--
动漫Id
]

DomainEvent("动漫已下架") [
动漫已下架
--字段--
动漫Id
]

DomainEvent("动漫已上架") [
动漫已上架
--字段--
动漫Id
]

DomainEvent("动漫已删除") [
动漫已删除
--字段--
动漫Id
]

DomainEvent("评论已新增") [
评论已新增
----
评论标识
]

DomainEvent("评论已通过审核") [
评论通过审核
----
评论标识
]

DomainEvent("评论未通过审核") [
评论未通过审核
----
评论标识
]

DomainEvent("评论已被屏蔽") [
评论已被屏蔽
----
评论标识
]

DomainEvent("评论已被移除") [
评论已被移除
----
评论标识
]


Command("用户注册") [
用户注册
--规则--
用户账号不存在
--字段--
用户标识
]

Command("用户激活") [
用户激活
--规则--
用户账号未激活
--字段--
用户标识
]

Command("用户重置密码") [
用户重置密码
--规则--
用户账号正常
--字段--
用户标识
]

Command("用户注销") [
用户注销
--规则--
用户账号正常
--字段--
用户标识
]

Command("锁定用户账号") [
锁定用户账号
--规则--
用户账号正常
--字段--
用户标识
]

Command("恢复用户账号") [
恢复用户账号
--规则--
用户账号被锁定
--字段--
用户标识
]

DomainEvent("用户已注册") [
用户已注册
--字段--
用户标识
]

DomainEvent("用户已激活") [
用户已激活
--字段--
用户标识
]

DomainEvent("用户密码已重置") [
用户密码已重置
--字段--
用户标识
]

DomainEvent("用户已注销") [
用户已注销
--字段--
用户标识
]

DomainEvent("用户已锁定") [
用户已锁定
--字段--
用户标识
]

Command("创建动漫") [
创建动漫
--规则--
当前动漫没有被创建
动漫Id不能重复
--字段--
动漫Id
]

Command("管理上架")[
管理上架
--规则--
当前动漫没有被上架
--字段--
动漫Id
]

Command("管理下架")[
管理下架
--规则--
当前动漫已上架
--字段--
动漫Id
]

Command("删除动漫")[
删除动漫
--规则--
当前动漫已下架
当前动漫没有被删除
--字段--
动漫Id
]

Command("新增用户信息")[
新增用户信息
--规则--
用户不能重复
--字段--
用户标识
]

Command("审批评论")[
审批评论
]

Command("删除评论")[
删除评论
]

Command("新增评论") [
新增评论
]

Command("举报评论")[
举报评论
]

Aggregate("动漫聚合")[
动漫聚合
--id--
动漫Id
--fields--
是否上架
是否删除
--methods--
是否可上架
]

Aggregate("评论聚合")[
评论聚合
--id--
评论Id
--fields--
是否屏蔽
是否已删除
]

Aggregate("用户聚合")[
用户聚合
--id--
用户表示
--fields--
是否禁用
是否激活
]

ReadModel("评论记录")[
评论记录
----
评论标识
评论内容
]

ReadModel("动漫信息")[
动漫信息
----
评论标识
评论内容
]

ReadModel("用户信息")[
用户信息
----
用户标识
用户名称
]


动漫已创建 -down-> 动漫信息
动漫已上架 -down-> 动漫信息
动漫已下架 -down-> 动漫信息
动漫已删除 -down-> 动漫信息

管理员 -down-> 创建动漫
管理员 -down-> 管理下架
管理员 -down-> 删除动漫

删除动漫 -down-> 动漫聚合
动漫聚合 -down-> 动漫已删除

管理下架 -down-> 动漫聚合
动漫聚合 -down-> 动漫已下架

管理员 -down-> 管理上架
管理上架 -down-> 动漫聚合
动漫聚合 -down-> 动漫已上架

创建动漫 -down-> 动漫聚合
动漫聚合 -down-> 动漫已创建
用户 -down-> 新增评论

评论聚合 -down-> 评论已被移除
评论聚合 -down-> 评论已被屏蔽
评论聚合 -down-> 评论未通过审核
评论聚合 -down-> 评论已通过审核
新增评论 -down-> 评论聚合
评论聚合 -down-> 评论已新增

用户 -down-> 删除评论
用户 -down-> 举报评论
用户 -down-> 审批评论
举报评论 -down-> 评论聚合
删除评论 -down-> 评论聚合
审批评论 -down-> 评论聚合
新增用户信息 -down-> 用户聚合


锁定用户账号 -down-> 用户聚合
恢复用户账号 -down-> 用户聚合
用户激活 -down-> 用户聚合
用户注销 -down-> 用户聚合
用户重置密码 -down-> 用户聚合
用户注册 -down-> 用户聚合

用户聚合 -down-> 用户已注册
用户聚合 -down-> 用户已激活
用户聚合 -down-> 用户密码已重置
用户聚合 -down-> 用户已注销
用户聚合 -down-> 用户已锁定

用户已注册 -down-> 用户信息
用户已激活 -down-> 用户信息
用户密码已重置 -down-> 用户信息
用户已注销 -down-> 用户信息
用户已锁定 -down-> 用户信息

评论已新增 -down-> 评论记录
评论已被移除 -down-> 评论记录
评论未通过审核 -down-> 评论记录
评论已通过审核 -down-> 评论记录
评论已被屏蔽 -down-> 评论记录
@enduml
