// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.version.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.system.version.Version;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.String;
import lombok.AccessLevel;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Schema
@Data
@EqualsAndHashCode(
        callSuper = true
)
@NoArgsConstructor(
        access = AccessLevel.PROTECTED
)
public class VersionVO extends AbstractBaseJpaVO {
    @Schema(
            title = "code"
    )
    private String code;

    @Schema(
            title = "name"
    )
    private String name;

    @Schema(
            title = "description"
    )
    private String description;

    public VersionVO(Version source) {
        super();
        this.setCode(source.getCode());
        this.setName(source.getName());
        this.setDescription(source.getDescription());
    }
}
