// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.version.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.system.version.Version;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.String;

import lombok.Data;

@Schema
@Data
public class VersionVO extends AbstractBaseJpaVO {
    @Schema(
            title = "Code",
            description = ""
    )
    private String code;

    @Schema(
            title = "Name",
            description = ""
    )
    private String name;

    @Schema(
            title = "Description",
            description = ""
    )
    private String description;

    protected VersionVO() {
    }

    public VersionVO(Version source) {
        super();
        this.setCode(source.getCode());
        this.setName(source.getName());
        this.setDescription(source.getDescription());
    }
}
