// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.tag.updater;

import cn.chenyunlong.qing.domain.anime.tag.AnimeTag;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;

import lombok.Data;

@Schema
@Data
public class AnimeTagUpdater {
    @Schema(
            title = "name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "description",
            description = "description"
    )
    private String description;

    @Schema(
            title = "orderNo",
            description = "orderNo"
    )
    private Integer orderNo;

    private Long id;

    public void updateAnimeTag(AnimeTag param) {
        Optional.ofNullable(getName()).ifPresent(param::setName);
        Optional.ofNullable(getDescription()).ifPresent(param::setDescription);
        Optional.ofNullable(getOrderNo()).ifPresent(param::setOrderNo);
    }
}
