// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.user.third.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Integer;
import java.lang.Long;
import java.lang.String;

import lombok.Data;

@Schema
@Data
public class ThirdUserUpdateRequest implements Request {
    @Schema(
            title = "userId",
            description = "userId"
    )
    private Long userId;

    @Schema(
            title = "uid",
            description = "uid"
    )
    private String uid;

    @Schema(
            title = "appType",
            description = "appType"
    )
    private String appType;

    @Schema(
            title = "accessToken",
            description = "accessToken"
    )
    private String accessToken;

    @Schema(
            title = "accessExpire",
            description = "accessExpire"
    )
    private Integer accessExpire;

    private Long id;
}
