// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.user.third.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class ThirdUserUpdateRequest implements Request {
    @Schema(
            title = "userId"
    )
    private Long userId;

    @Schema(
            title = "uid"
    )
    private String uid;

    @Schema(
            title = "appType"
    )
    private String appType;

    @Schema(
            title = "accessToken"
    )
    private String accessToken;

    @Schema(
            title = "accessExpire"
    )
    private Integer accessExpire;

    private Long id;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getAppType() {
        return appType;
    }

    public void setAppType(String appType) {
        this.appType = appType;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public Integer getAccessExpire() {
        return accessExpire;
    }

    public void setAccessExpire(Integer accessExpire) {
        this.accessExpire = accessExpire;
    }

    public Long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
