// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.recommend.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDateTime;

@Schema
public class RecommendResponse extends AbstractJpaResponse {
    @Schema(
            title = "aid"
    )
    private Long aid;

    @Schema(
            title = "reason"
    )
    private String reason;

    @Schema(
            title = "date"
    )
    private LocalDateTime date;

    public Long getAid() {
        return aid;
    }

    public void setAid(Long aid) {
        this.aid = aid;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public LocalDateTime getDate() {
        return date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }
}
