// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.config.query;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class SysConfigQuery {
}
