server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: qing-service-web
  graphql:
    graphiql:
      enabled: true
qing:
  api:
    description: QING-WEB-APPLICATION
  security:
    authing:
      auth-login-url-prefix: /api/auth2/authorization
logging:
  level:
    root: info
# Knife4j 配置
knife4j:
  enable: true
  openapi:
    title: QING动漫管理系统API
    description: QING动漫管理系统的RESTful API文档
    version: @project.version@
    concat: 陈云龙
  setting:
    language: zh_cn
