// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.system.config.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.system.config.SysConfig;

public interface SysConfigRepository extends BaseRepository<SysConfig, Long> {
}
