// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.type.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.anime.type.AnimeType;

public interface AnimeTypeRepository extends BaseRepository<AnimeType, Long> {
}
