// ---Auto Generated by Qing-Generator --
package cn.chenyunlong.qing.samples.codegen.domain.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.samples.codegen.domain.TestDomain;
import java.lang.Long;

public interface TestDomainRepository extends BaseRepository<TestDomain, Long> {
}
