// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.attachment.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class AttachmentResponse extends AbstractJpaResponse {
    @Schema(
            title = "attachmentId"
    )
    private Integer attachmentId;

    @Schema(
            title = "attachmentName"
    )
    private String attachmentName;

    @Schema(
            title = "attachmentUrl"
    )
    private String attachmentUrl;

    public Integer getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    public String getAttachmentName() {
        return attachmentName;
    }

    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName;
    }

    public String getAttachmentUrl() {
        return attachmentUrl;
    }

    public void setAttachmentUrl(String attachmentUrl) {
        this.attachmentUrl = attachmentUrl;
    }
}
