// Auto Generated by Qing Code Generator
// Do not modify this file manually
// Generated at: 2025-08-22T16:16:17.163775
package cn.chenyunlong.qing.anime.domain.product.dto.query;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * Product查询条件对象
 *
 * @author 代码生成器
 * @since 2025-08-22 16:16:17
 */
@Schema(
        name = "ProductQuery",
        description = "Product查询条件对象"
)
@Data
public class ProductQuery {
}
