/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.playlist.controller;

import cn.chenyunlong.common.constants.CodeEnum;
import cn.chenyunlong.common.model.JsonObject;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.common.model.PageResult;
import cn.chenyunlong.qing.domain.anime.playlist.creator.PlaylistCreator;
import cn.chenyunlong.qing.domain.anime.playlist.mapper.PlaylistMapper;
import cn.chenyunlong.qing.domain.anime.playlist.query.PlaylistQuery;
import cn.chenyunlong.qing.domain.anime.playlist.request.PlaylistCreateRequest;
import cn.chenyunlong.qing.domain.anime.playlist.request.PlaylistQueryRequest;
import cn.chenyunlong.qing.domain.anime.playlist.request.PlaylistUpdateRequest;
import cn.chenyunlong.qing.domain.anime.playlist.response.PlaylistResponse;
import cn.chenyunlong.qing.domain.anime.playlist.service.IPlaylistService;
import cn.chenyunlong.qing.domain.anime.playlist.updater.PlaylistUpdater;
import cn.chenyunlong.qing.domain.anime.playlist.vo.PlaylistVO;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.*;

import java.util.stream.Collectors;

@RestController
@Slf4j
@RequestMapping("playlist/v1")
@RequiredArgsConstructor
public class PlaylistController {
    private final IPlaylistService playlistService;

    /**
     * createRequest
     */
    @PostMapping("createPlaylist")
    public JsonObject<Long> createPlaylist(@RequestBody PlaylistCreateRequest request) {
        PlaylistCreator creator = PlaylistMapper.INSTANCE.request2Dto(request);
        return JsonObject.success(playlistService.createPlaylist(creator));
    }

    /**
     * update request
     */
    @PostMapping("updatePlaylist")
    public JsonObject<String> updatePlaylist(@RequestBody PlaylistUpdateRequest request) {
        PlaylistUpdater updater = PlaylistMapper.INSTANCE.request2Updater(request);
        playlistService.updatePlaylist(updater);
        return JsonObject.success(CodeEnum.Success.getName());
    }

    /**
     * valid
     */
    @PostMapping("valid/{id}")
    public JsonObject<String> validPlaylist(@PathVariable Long id) {
        playlistService.validPlaylist(id);
        return JsonObject.success(CodeEnum.Success.getName());
    }

    /**
     * invalid
     */
    @PostMapping("invalid/{id}")
    public JsonObject<String> invalidPlaylist(@PathVariable Long id) {
        playlistService.invalidPlaylist(id);
        return JsonObject.success(CodeEnum.Success.getName());
    }

    /**
     * findById
     */
    @GetMapping("findById/{id}")
    public JsonObject<PlaylistResponse> findById(@PathVariable Long id) {
        PlaylistVO vo = playlistService.findById(id);
        PlaylistResponse response = PlaylistMapper.INSTANCE.vo2CustomResponse(vo);
        return JsonObject.success(response);
    }

    /**
     * findByPage request
     */
    @PostMapping("findByPage")
    public JsonObject<PageResult<PlaylistResponse>> findByPage(
            @RequestBody PageRequestWrapper<PlaylistQueryRequest> request) {
        PageRequestWrapper<PlaylistQuery> wrapper = new PageRequestWrapper<>();
        wrapper.setBean(PlaylistMapper.INSTANCE.request2Query(request.getBean()));
        wrapper.setSorts(request.getSorts());
        wrapper.setPageSize(request.getPageSize());
        wrapper.setPage(request.getPage());
        Page<PlaylistVO> page = playlistService.findByPage(wrapper);
        return JsonObject.success(
                PageResult.of(
                        page.getContent().stream()
                                .map(vo -> PlaylistMapper.INSTANCE.vo2CustomResponse(vo))
                                .collect(Collectors.toList()),
                        page.getTotalElements(),
                        page.getSize(),
                        page.getNumber())
        );
    }
}
