// ---Auto Generated by Qing-Generator --
package cn.chenyunlong.qing.domain.user.service;

import cn.chenyunlong.common.model.JsonResult;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.common.model.PageResult;
import cn.chenyunlong.qing.domain.user.request.UserCreateRequest;
import cn.chenyunlong.qing.domain.user.request.UserQueryRequest;
import cn.chenyunlong.qing.domain.user.request.UserUpdateRequest;
import cn.chenyunlong.qing.domain.user.response.UserResponse;
import java.lang.Long;
import java.lang.String;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

@FeignClient(
        value = "stanic",
        contextId = "userClient",
        path = "user/v1"
)
public interface UserFeignService {
    /**
     * createRequest
     */
    @PostMapping("createUser")
    JsonResult<Long> createUser(@RequestBody UserCreateRequest request);

    /**
     * update request
     */
    @PostMapping("updateUser")
    JsonResult<String> updateUser(@RequestBody UserUpdateRequest request);

    /**
     * valid
     */
    @PostMapping("valid/{id}")
    JsonResult<String> validUser(@PathVariable("id") Long id);

    /**
     * invalid
     */
    @PostMapping("invalid/{id}")
    JsonResult<String> invalidUser(@PathVariable("id") Long id);

    /**
     * findById
     */
    @GetMapping("findById/{id}")
    JsonResult<UserResponse> findById(@PathVariable("id") Long id);

    /**
     * findByPage request
     */
    @PostMapping("findByPage")
    JsonResult<PageResult<UserResponse>> findByPage(
            @RequestBody PageRequestWrapper<UserQueryRequest> request);
}
