// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.comment.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class CommentUpdateRequest implements Request {
    @Schema(
            title = "Cid",
            description = "cid"
    )
    private Long cid;

    @Schema(
            title = "Username",
            description = "username"
    )
    private String username;

    @Schema(
            title = "Content",
            description = "content"
    )
    private String content;

    @Schema(
            title = "IpAddress",
            description = "ipAddress"
    )
    private String ipAddress;

    private Long id;
}
