// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.district.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.district.District;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class DistrictVO extends AbstractBaseJpaVO {
    @Schema(
            title = "Name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "Code",
            description = "code"
    )
    private String code;

    @Schema(
            title = "Description",
            description = "description"
    )
    private String description;

    protected DistrictVO() {
    }

    public DistrictVO(District source) {
        super();
        this.setName(source.getName());
        this.setCode(source.getCode());
        this.setDescription(source.getDescription());
    }
}
