// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.district.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.district.District;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.String;

import lombok.AccessLevel;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Schema
@Data
@EqualsAndHashCode(
        callSuper = true
)
@NoArgsConstructor(
        access = AccessLevel.PROTECTED
)
public class DistrictVO extends AbstractBaseJpaVO {
    @Schema(
            title = "name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "code",
            description = "code"
    )
    private String code;

    @Schema(
            title = "description",
            description = "description"
    )
    private String description;

    public DistrictVO(District source) {
        super();
        this.setName(source.getName());
        this.setCode(source.getCode());
        this.setDescription(source.getDescription());
    }
}
