server:
  port: 8088
spring:
  application:
    name: qing-service-auth
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://192.168.3.10:5433/qing
    username: postgres
    password: admin@123456
    driver-class-name: org.postgresql.Driver
qing:
  api:
    description: QING-AUTH-SERVICE
  security:
    authing:
      auth-login-url-prefix: /api/auth2/authorization

jwt:
  secret: qingSecretKey
  expiration: 18000 # 5小时
logging:
  level:
    root: info
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: warning
  client:
    ts:
      path: /ts.zip
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: Qing Web Service
          description: Restore the DTO explosion that was eliminated by server-side developers
          version: 1.0
