// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.district.updater;

import cn.chenyunlong.qing.domain.district.District;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.Optional;

@Schema
@Data
public class DistrictUpdater {
    @Schema(
            title = "Name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "Code",
            description = "code"
    )
    private String code;

    @Schema(
            title = "Description",
            description = "description"
    )
    private String description;

    private Long id;

    public void updateDistrict(District param) {
        Optional.ofNullable(getName()).ifPresent(v -> param.setName(v));
        Optional.ofNullable(getCode()).ifPresent(v -> param.setCode(v));
        Optional.ofNullable(getDescription()).ifPresent(v -> param.setDescription(v));
    }
}
