// Auto Generated by Qing Code Generator
// Do not modify this file manually
// Generated at: 2025-08-23T00:45:59.224294100
package cn.chenyunlong.codegen.example.domain.dto.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@Schema
@EqualsAndHashCode(
        callSuper = true
)
public class OrderResponse extends AbstractJpaResponse {
    @Schema(
            description = "orderNumber"
    )
    private String orderNumber;

    @Schema(
            description = "amount"
    )
    private Double amount;

    @Schema(
            description = "status"
    )
    private String status;
}
