// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.recommend.service;

import cn.chenyunlong.common.model.JsonResult;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.common.model.PageResult;
import cn.chenyunlong.qing.domain.anime.recommend.request.RecommendCreateRequest;
import cn.chenyunlong.qing.domain.anime.recommend.request.RecommendQueryRequest;
import cn.chenyunlong.qing.domain.anime.recommend.request.RecommendUpdateRequest;
import cn.chenyunlong.qing.domain.anime.recommend.response.RecommendResponse;

import java.lang.Long;
import java.lang.String;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

@FeignClient(
        value = "xxxSrv",
        contextId = "recommendClient",
        path = "recommend/v1"
)
public interface RecommendFeignService {
    /**
     * createRequest
     */
    @PostMapping("createRecommend")
    JsonResult<Long> createRecommend(@RequestBody RecommendCreateRequest request);

    /**
     * update request
     */
    @PostMapping("updateRecommend")
    JsonResult<String> updateRecommend(@RequestBody RecommendUpdateRequest request);

    /**
     * valid
     */
    @PostMapping("valid/{id}")
    JsonResult<String> validRecommend(@PathVariable("id") Long id);

    /**
     * invalid
     */
    @PostMapping("invalid/{id}")
    JsonResult<String> invalidRecommend(@PathVariable("id") Long id);

    /**
     * findById
     */
    @GetMapping("findById/{id}")
    JsonResult<RecommendResponse> findById(@PathVariable("id") Long id);

    /**
     * findByPage request
     */
    @PostMapping("findByPage")
    JsonResult<PageResult<RecommendResponse>> findByPage(
            @RequestBody PageRequestWrapper<RecommendQueryRequest> request);
}
