// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.file.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class UploadFileCreateRequest implements Request {
    @Schema(
            title = "fileId"
    )
    private Long fileId;

    @Schema(
            title = "fileName"
    )
    private String fileName;

    @Schema(
            title = "mimeType"
    )
    private String mimeType;

    @Schema(
            title = "url"
    )
    private String url;

    @Schema(
            title = "fileSize"
    )
    private Long fileSize;

    public Long getFileId() {
        return fileId;
    }

    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }
}
