// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.file.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Long;
import java.lang.String;

import lombok.Data;

@Schema
@Data
public class UploadFileCreateRequest implements Request {
    @Schema(
            title = "fileId",
            description = "fileId"
    )
    private Long fileId;

    @Schema(
            title = "fileName",
            description = "fileName"
    )
    private String fileName;

    @Schema(
            title = "mimeType",
            description = "mimeType"
    )
    private String mimeType;

    @Schema(
            title = "url",
            description = "url"
    )
    private String url;

    @Schema(
            title = "fileSize",
            description = "fileSize"
    )
    private Long fileSize;
}
