/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.activity.mapper;

import cn.chenyunlong.common.mapper.DateMapper;
import cn.chenyunlong.common.mapper.GenericEnumMapper;
import cn.chenyunlong.qing.domain.activity.Activity;
import cn.chenyunlong.qing.domain.activity.creator.ActivityCreator;
import cn.chenyunlong.qing.domain.activity.query.ActivityQuery;
import cn.chenyunlong.qing.domain.activity.request.ActivityCreateRequest;
import cn.chenyunlong.qing.domain.activity.request.ActivityQueryRequest;
import cn.chenyunlong.qing.domain.activity.request.ActivityUpdateRequest;
import cn.chenyunlong.qing.domain.activity.response.ActivityResponse;
import cn.chenyunlong.qing.domain.activity.updater.ActivityUpdater;
import cn.chenyunlong.qing.domain.activity.vo.ActivityVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
        uses = {
                GenericEnumMapper.class,
                DateMapper.class
        }
)
public interface ActivityMapper {
    ActivityMapper INSTANCE = Mappers.getMapper(ActivityMapper.class);

    Activity dtoToEntity(ActivityCreator dto);

    ActivityUpdater request2Updater(ActivityUpdateRequest request);

    ActivityCreator request2Dto(ActivityCreateRequest request);

    ActivityQuery request2Query(ActivityQueryRequest request);

    ActivityResponse vo2Response(ActivityVO vo);

    default ActivityResponse vo2CustomResponse(ActivityVO vo) {
        ActivityResponse response = vo2Response(vo);
        return response;
    }
}
