// ---Auto Generated by Qing-Generator --
package cn.chenyunlong.qing.domain.anime.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class AnimeQueryRequest implements Request {
}
