server:
  port: 8087
spring:
  application:
    name: qing-service-llm
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: qing-llm
    password: 123456
    url: jdbc:postgresql://192.168.3.112:5432/qing-llm
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
