server:
  port: 8087
spring:
  application:
    name: qing-service-llm
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: qing-llm
    password: 123456
    url: jdbc:postgresql://192.168.3.112:5432/qing-llm
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jdbc:
          batch_size: 50
  main:
    lazy-initialization: true
  jackson:
    serialization:
      fail-on-empty-beans: false
baseEnum:
  basePackage: cn.chenyunlong.qing.service.llm.enums
langchain4j:
  open-ai:
    chat-model:
      api-key: 123123123
      model-name: gpt-4o
      log-requests: true
      log-responses: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: read_only
qianji:
  file:
    storage-path: /data/qianji-files
    max-size: 20971520
    allowed-types: csv,xlsx,xls
logging:
  pattern:
    level: '%5p [${spring.application.name:},%mdc{trace_id:-},%mdc{span_id:-}]'
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30
      total-size-cap: 1GB
