// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.sign.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.sign.Sign;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class SignVO extends AbstractBaseJpaVO {
    @Schema(
            title = "UserId",
            description = ""
    )
    private Long userId;

    @Schema(
            title = "DateMonth",
            description = ""
    )
    private Long dateMonth;

    @Schema(
            title = "Mask",
            description = ""
    )
    private Integer mask;

    @Schema(
            title = "ContinueSignMonth",
            description = ""
    )
    private Integer continueSignMonth;

    protected SignVO() {
    }

    public SignVO(Sign source) {
        super();
        this.setUserId(source.getUserId());
        this.setDateMonth(source.getDateMonth());
        this.setMask(source.getMask());
        this.setContinueSignMonth(source.getContinueSignMonth());
    }
}
