/*
 * Copyright (c) 2019-2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          https://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.mapper;

import cn.chenyunlong.qing.domain.anime.AnimeInfo;
import cn.chenyunlong.qing.domain.anime.creator.AnimeInfoCreator;
import cn.chenyunlong.qing.domain.anime.query.AnimeInfoQuery;
import cn.chenyunlong.qing.domain.anime.request.AnimeInfoCreateRequest;
import cn.chenyunlong.qing.domain.anime.request.AnimeInfoQueryRequest;
import cn.chenyunlong.qing.domain.anime.request.AnimeInfoUpdateRequest;
import cn.chenyunlong.qing.domain.anime.response.AnimeInfoResponse;
import cn.chenyunlong.qing.domain.anime.updater.AnimeInfoUpdater;
import cn.chenyunlong.qing.domain.anime.vo.AnimeInfoVO;
import cn.hutool.core.bean.BeanUtil;

public interface AnimeInfoMapper {
    AnimeInfoMapper INSTANCE = new AnimeInfoMapper() {
    };

    default AnimeInfo dtoToEntity(AnimeInfoCreator dto) {
        return BeanUtil.copyProperties(dto, AnimeInfo.class);
    }

    default AnimeInfoVO entityToVo(AnimeInfo animeInfo) {
        return BeanUtil.copyProperties(animeInfo, AnimeInfoVO.class);
    }

    default AnimeInfoUpdater request2Updater(AnimeInfoUpdateRequest request) {
        return BeanUtil.copyProperties(request, AnimeInfoUpdater.class);
    }

    default AnimeInfoCreator request2Dto(AnimeInfoCreateRequest request) {
        return BeanUtil.copyProperties(request, AnimeInfoCreator.class);
    }

    default AnimeInfoQuery request2Query(AnimeInfoQueryRequest request) {
        return BeanUtil.copyProperties(request, AnimeInfoQuery.class);
    }

    default AnimeInfoResponse vo2Response(AnimeInfoVO vo) {
        return BeanUtil.copyProperties(vo, AnimeInfoResponse.class);
    }

    default AnimeInfoResponse vo2CustomResponse(AnimeInfoVO vo) {
        return vo2Response(vo);
    }
}
