version: '3.8'


services:
  # 分布式缓存服务
  redis:
    image: redis:7.0-alpine
    container_name: qing-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

  # 关系型数据库
  postgres:
    image: postgres:15-alpine
    container_name: qing-postgres
    environment:
      POSTGRES_DB: qingdb
      POSTGRES_USER: qinguser
      POSTGRES_PASSWORD: qingpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U qinguser" ]
      interval: 5s
      timeout: 5s
      retries: 5


  # 对象存储服务
  minio:
    image: minio/minio:latest
    container_name: qing-minio
    environment:
      MINIO_ROOT_USER: qingminio
      MINIO_ROOT_PASSWORD: qingminio123
      MINIO_DEFAULT_BUCKETS: "qing-bucket"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API端口
      - "9001:9001"  # 控制台端口
    volumes:
      - minio_data:/data
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  consul:
    image: consul:latest
    container_name: consul-server
    expose:
      - 8500
      - 8300
    ports:
      - "8500:8500"
      - "8300:8300"
    networks:
      - backend-network
    restart: always

volumes:
  redis_data:
  postgres_data:
  minio_data:

networks:
  backend-network:
    driver: bridge
