server:
  port: 8080
spring:
  application:
    name: qing-service-auth
  datasource:
    driver-class-name: org.postgresql.Driver
    username: qing-auth
    password: 123456
    url: jdbc:postgresql://192.168.3.112:5432/qing-auth
  data:
    redis:
      host: 192.168.3.112
      port: 6379
      database: 0
      password: 123456
  rabbitmq:
    host: 192.168.3.112
    username: rabbitmq
    password: 123456
  jackson:
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.qq.com
    port: 587
    username: 1576302867@qq.com
    password: 123456
    ssl:
      enabled: true
qing:
  api:
    description: QING-AUTH-SERVICE

jwt:
  secret: qingSecretKey
  expiration: 18000 # 5小时
logging:
  level:
    root: info
