// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.activity.response;

import cn.chenyunlong.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class ActivityResponse extends AbstractJpaResponse {
    @Schema(
            title = "ActivityId"
    )
    private String activityId;

    @Schema(
            title = "Username",
            description = "username"
    )
    private String username;

    @Schema(
            title = "ActivityName",
            description = "activityName"
    )
    private String activityName;

    @Schema(
            title = "ActivityContent",
            description = "activityContent"
    )
    private String activityContent;

    @Schema(
            title = "AttachmentAddress",
            description = "attachmentAddress"
    )
    private String attachmentAddress;

    @Schema(
            title = "AttachmentType",
            description = "attachmentType"
    )
    private Integer attachmentType;

    @Schema(
            title = "PublishState",
            description = "publishState"
    )
    private Integer publishState;
}
