// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.tag.creator;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class AnimeTagCreator {
    @Schema(
            title = "Name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "Description",
            description = "description"
    )
    private String description;

    @Schema(
            title = "OrderNo",
            description = "orderNo"
    )
    private Integer orderNo;
}
