// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.system.job.job.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.system.job.job.SysJob;

public interface SysJobRepository extends BaseRepository<SysJob, Long> {
}
