// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.user.user.request;

import cn.chenyunlong.common.model.Request;
import cn.chenyunlong.qing.infrastructure.enums.MFAType;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Long;
import java.lang.String;
import java.time.LocalDateTime;

import lombok.Data;

@Schema
@Data
public class UserUpdateRequest implements Request {
    @Schema(
            title = "uid",
            description = "uid"
    )
    private Long uid;

    @Schema(
            title = "username",
            description = "username"
    )
    private String username;

    @Schema(
            title = "nickname",
            description = "nickname"
    )
    private String nickname;

    @Schema(
            title = "password",
            description = "password"
    )
    private String password;

    @Schema(
            title = "phone",
            description = "phone"
    )
    private String phone;

    @Schema(
            title = "email",
            description = "email"
    )
    private String email;

    @Schema(
            title = "avatar",
            description = "avatar"
    )
    private String avatar;

    @Schema(
            title = "description",
            description = "description"
    )
    private String description;

    @Schema(
            title = "expireTime",
            description = "expireTime"
    )
    private LocalDateTime expireTime;

    @Schema(
            title = "mfaType",
            description = "mfaType"
    )
    private MFAType mfaType;

    @Schema(
            title = "mfaKey",
            description = "mfaKey"
    )
    private String mfaKey;

    private Long id;
}
