// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.version.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.String;

import lombok.Data;

@Schema
@Data
public class VersionQueryRequest implements Request {
    @Schema(
            title = "Name"
    )
    private String name;
}
