// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.version.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class VersionCreateRequest implements Request {
    @Schema(
            title = "Code"
    )
    private String code;

    @Schema(
            title = "Name"
    )
    private String name;

    @Schema(
            title = "Description"
    )
    private String description;
}
