// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.district.query;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class DistrictQuery {
}
