// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.job.job.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Long;
import java.lang.String;

import lombok.Data;

@Schema
@Data
public class SysJobCreateRequest implements Request {
    @Schema(
            title = "jobId",
            description = "jobId"
    )
    private Long jobId;

    @Schema(
            title = "jobName",
            description = "jobName"
    )
    private String jobName;

    @Schema(
            title = "jobGroup",
            description = "jobGroup"
    )
    private String jobGroup;

    @Schema(
            title = "invokeTarget",
            description = "invokeTarget"
    )
    private String invokeTarget;

    @Schema(
            title = "cronExpression",
            description = "cronExpression"
    )
    private String cronExpression;

    @Schema(
            title = "misfirePolicy",
            description = "misfirePolicy"
    )
    private String misfirePolicy;

    @Schema(
            title = "concurrent",
            description = "concurrent"
    )
    private String concurrent;

    @Schema(
            title = "status",
            description = "status"
    )
    private String status;
}
