// ---Auto Generated by Qing-Generator --
package cn.chenyunlong.qing.domain.anime.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.anime.Anime;
import java.lang.Long;

public interface AnimeRepository extends BaseRepository<Anime, Long> {
}
