// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.anime.AnimeInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface AnimeInfoRepository extends BaseRepository<AnimeInfo, Long> {
}
