// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.type.service.impl;

import cn.chenyunlong.common.constants.CodeEnum;
import cn.chenyunlong.common.exception.BusinessException;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.jpa.support.EntityOperations;
import cn.chenyunlong.jpa.support.domain.BaseEntity;
import cn.chenyunlong.qing.domain.anime.type.AnimeType;
import cn.chenyunlong.qing.domain.anime.type.creator.AnimeTypeCreator;
import cn.chenyunlong.qing.domain.anime.type.mapper.AnimeTypeMapper;
import cn.chenyunlong.qing.domain.anime.type.query.AnimeTypeQuery;
import cn.chenyunlong.qing.domain.anime.type.repository.AnimeTypeRepository;
import cn.chenyunlong.qing.domain.anime.type.service.IAnimeTypeService;
import cn.chenyunlong.qing.domain.anime.type.updater.AnimeTypeUpdater;
import cn.chenyunlong.qing.domain.anime.type.vo.AnimeTypeVO;
import com.querydsl.core.BooleanBuilder;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;
import java.util.stream.Collectors;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class AnimeTypeServiceImpl implements IAnimeTypeService {
    private final AnimeTypeRepository animeTypeRepository;

    /**
     * createImpl
     */
    @Override
    public Long createAnimeType(AnimeTypeCreator creator) {
        Optional<AnimeType> animeType = EntityOperations.doCreate(animeTypeRepository)
                .create(() -> AnimeTypeMapper.INSTANCE.dtoToEntity(creator))
                .update(AnimeType::init)
                .execute();
        return animeType.isPresent() ? animeType.get().getId() : 0;
    }

    /**
     * update
     */
    @Override
    public void updateAnimeType(AnimeTypeUpdater updater) {
        EntityOperations.doUpdate(animeTypeRepository)
                .loadById(updater.getId())
                .update(updater::updateAnimeType)
                .execute();
    }

    /**
     * valid
     */
    @Override
    public void validAnimeType(Long id) {
        EntityOperations.doUpdate(animeTypeRepository)
                .loadById(id)
                .update(BaseEntity::valid)
                .execute();
    }

    /**
     * invalid
     */
    @Override
    public void invalidAnimeType(Long id) {
        EntityOperations.doUpdate(animeTypeRepository)
                .loadById(id)
                .update(BaseEntity::invalid)
                .execute();
    }

    /**
     * findById
     */
    @Override
    public AnimeTypeVO findById(Long id) {
        Optional<AnimeType> animeType = animeTypeRepository.findById(id);
        return new AnimeTypeVO(animeType.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
    }

    /**
     * findByPage
     */
    @Override
    public Page<AnimeTypeVO> findByPage(PageRequestWrapper<AnimeTypeQuery> query) {
        BooleanBuilder booleanBuilder = new BooleanBuilder();
        Page<AnimeType> page = animeTypeRepository.findAll(booleanBuilder,
                PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                        Sort.Direction.DESC, "createdAt")));
        return new PageImpl<>(page.getContent()
                .stream().map(AnimeTypeVO::new)
                .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
    }
}
