// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.file.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.file.UploadFile;

public interface UploadFileRepository extends BaseRepository<UploadFile, Long> {
}
