/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.user.user.creator;

import cn.chenyunlong.qing.infrastructure.enums.MFAType;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class UserCreator {
    @Schema(
            title = "Uid",
            description = "uid"
    )
    private Long uid;

    @Schema(
            title = "Username",
            description = "username"
    )
    private String username;

    @Schema(
            title = "Nickname",
            description = "nickname"
    )
    private String nickname;

    @Schema(
            title = "Password",
            description = "password"
    )
    private String password;

    @Schema(
            title = "Phone",
            description = "phone"
    )
    private String phone;

    @Schema(
            title = "Email",
            description = "email"
    )
    private String email;

    @Schema(
            title = "Avatar",
            description = "avatar"
    )
    private String avatar;

    @Schema(
            title = "Description",
            description = "description"
    )
    private String description;

    @Schema(
            title = "MfaType",
            description = "mfaType"
    )
    private MFAType mfaType;

    @Schema(
            title = "MfaKey",
            description = "mfaKey"
    )
    private String mfaKey;
}
