// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.anime.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.anime.anime.AnimeInfo;

public interface AnimeInfoRepository extends BaseRepository<AnimeInfo, Long> {
}
