// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.job.log.creator;

import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Long;
import java.lang.String;

import lombok.Data;

@Schema
@Data
public class SysJobLogCreator {
    @Schema(
            title = "jobLogId",
            description = "jobLogId"
    )
    private Long jobLogId;

    @Schema(
            title = "jobName",
            description = "jobName"
    )
    private String jobName;

    @Schema(
            title = "jobGroup",
            description = "jobGroup"
    )
    private String jobGroup;

    @Schema(
            title = "invokeTarget",
            description = "invokeTarget"
    )
    private String invokeTarget;

    @Schema(
            title = "jobMessage",
            description = "jobMessage"
    )
    private String jobMessage;

    @Schema(
            title = "status",
            description = "status"
    )
    private String status;

    @Schema(
            title = "exceptionInfo",
            description = "exceptionInfo"
    )
    private String exceptionInfo;
}
