// ---Auto Generated by Qing-Generator --
package cn.chenyunlong.qing.domain.attachement.repository;

import cn.chenyunlong.jpa.support.BaseRepository;
import cn.chenyunlong.qing.domain.attachement.Attachment;
import java.lang.Long;

public interface AttachmentRepository extends BaseRepository<Attachment, Long> {
}
