// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.permission.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.permission.Permission;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class PermissionVO extends AbstractBaseJpaVO {
    @Schema(
            title = "Name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "Description",
            description = "description"
    )
    private String description;

    protected PermissionVO() {
    }

    public PermissionVO(Permission source) {
        super();
        this.setName(source.getName());
        this.setDescription(source.getDescription());
    }
}
