/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.type.mapper;

import cn.chenyunlong.common.mapper.DateMapper;
import cn.chenyunlong.common.mapper.GenericEnumMapper;
import cn.chenyunlong.qing.domain.anime.type.AnimeType;
import cn.chenyunlong.qing.domain.anime.type.creator.AnimeTypeCreator;
import cn.chenyunlong.qing.domain.anime.type.query.AnimeTypeQuery;
import cn.chenyunlong.qing.domain.anime.type.request.AnimeTypeCreateRequest;
import cn.chenyunlong.qing.domain.anime.type.request.AnimeTypeQueryRequest;
import cn.chenyunlong.qing.domain.anime.type.request.AnimeTypeUpdateRequest;
import cn.chenyunlong.qing.domain.anime.type.response.AnimeTypeResponse;
import cn.chenyunlong.qing.domain.anime.type.updater.AnimeTypeUpdater;
import cn.chenyunlong.qing.domain.anime.type.vo.AnimeTypeVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
        uses = {
                GenericEnumMapper.class,
                DateMapper.class
        }
)
public interface AnimeTypeMapper {
    AnimeTypeMapper INSTANCE = Mappers.getMapper(AnimeTypeMapper.class);

    AnimeType dtoToEntity(AnimeTypeCreator dto);

    AnimeTypeUpdater request2Updater(AnimeTypeUpdateRequest request);

    AnimeTypeCreator request2Dto(AnimeTypeCreateRequest request);

    AnimeTypeQuery request2Query(AnimeTypeQueryRequest request);

    AnimeTypeResponse vo2Response(AnimeTypeVO vo);

    default AnimeTypeResponse vo2CustomResponse(AnimeTypeVO vo) {
        AnimeTypeResponse response = vo2Response(vo);
        return response;
    }
}
