// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.comment.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.anime.comment.Comment;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Long;
import java.lang.String;

import lombok.AccessLevel;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

@Schema
@Data
@EqualsAndHashCode(
        callSuper = true
)
@NoArgsConstructor(
        access = AccessLevel.PROTECTED
)
public class CommentVO extends AbstractBaseJpaVO {
    @Schema(
            title = "cid",
            description = "cid"
    )
    private Long cid;

    @Schema(
            title = "username",
            description = "username"
    )
    private String username;

    @Schema(
            title = "content",
            description = "content"
    )
    private String content;

    @Schema(
            title = "ipAddress",
            description = "ipAddress"
    )
    private String ipAddress;

    public CommentVO(Comment source) {
        super();
        this.setCid(source.getCid());
        this.setUsername(source.getUsername());
        this.setContent(source.getContent());
        this.setIpAddress(source.getIpAddress());
    }
}
