// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.playlist.creator;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class PlaylistCreator {
    @Schema(
            title = "AnimeId",
            description = "animeId"
    )
    private Long animeId;

    @Schema(
            title = "Name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "Description",
            description = "description"
    )
    private String description;
}
