// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.attachment.vo;

import cn.chenyunlong.common.model.AbstractBaseJpaVO;
import cn.chenyunlong.qing.domain.anime.attachment.Attachment;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class AttachmentVO extends AbstractBaseJpaVO {
    @Schema(
            title = "AttachmentId",
            description = "attachmentId"
    )
    private Integer attachmentId;

    @Schema(
            title = "AttachmentName",
            description = "attachmentName"
    )
    private String attachmentName;

    @Schema(
            title = "AttachmentUrl",
            description = "attachmentUrl"
    )
    private String attachmentUrl;

    protected AttachmentVO() {
    }

    public AttachmentVO(Attachment source) {
        super();
        this.setAttachmentId(source.getAttachmentId());
        this.setAttachmentName(source.getAttachmentName());
        this.setAttachmentUrl(source.getAttachmentUrl());
    }
}
