// Auto Generated by Qing Code Generator
// Do not modify this file manually
// Generated at: 2025-08-23T00:45:59.226294600
package cn.chenyunlong.codegen.example.domain.dto.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class OrderCreateRequest implements Request {
    @Schema(
            description = "orderNumber"
    )
    private String orderNumber;

    @Schema(
            description = "amount"
    )
    private Double amount;

    @Schema(
            description = "status"
    )
    private String status;
}
