version: "3"

services:
  consul:
    image: consul:latest
    container_name: consul
    restart: always
    volumes:
      - ./db:/consul/data
    ports:
      - "8300:8300"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=STANIC@POSTGRES@PASS
      - POSTGRES_USER=qing
      - POSTGRES_DB=qing
      - PGUSER=root
