// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.comment.creator;

import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.Long;
import java.lang.String;

import lombok.Data;

@Schema
@Data
public class CommentCreator {
    @Schema(
            title = "cid",
            description = "cid"
    )
    private Long cid;

    @Schema(
            title = "username",
            description = "username"
    )
    private String username;

    @Schema(
            title = "content",
            description = "content"
    )
    private String content;

    @Schema(
            title = "ipAddress",
            description = "ipAddress"
    )
    private String ipAddress;
}
