#!/bin/bash

case $1 in
start)
    # 启动应用的命令，成功返回 0，失败返回 1
    exit 0
    ;;
stop)
    # 停止应用的命令，成功返回 0，失败返回 1
    exit 0
    ;;
status)
    # 检查应用运行状态，运行中返回 0，未运行返回 3
    exit 0
    ;;
*)
    exit 1
    ;;
esac