// Auto Generated by Qing Code Generator
// Do not modify this file manually
// Generated at: 2025-08-22T03:43:26.945556600
package cn.chenyunlong.codegen.example.domain.repository;

import cn.chenyunlong.codegen.example.domain.Order;
import cn.chenyunlong.qing.domain.common.AggregateId;
import cn.chenyunlong.qing.domain.common.repository.BaseRepository;
import org.springframework.data.jpa.repository.JpaRepository;

public interface OrderRepository extends BaseRepository<Order, AggregateId>, JpaRepository<Order, AggregateId> {
}
