// Auto Generated by Qing Code Generator
// Do not modify this file manually
// Generated at: 2025-08-22T03:43:26.952556900

package cn.chenyunlong.codegen.example.domain.dto.creator;

import cn.chenyunlong.codegen.example.domain.User;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.String;
import lombok.Data;

@Schema
@Data
public class UserCreator {
    @Schema(
            title = "username"
    )
    private String username;

    @Schema(
            title = "email"
    )
    private String email;

    @Schema(
            title = "realName"
    )
    private String realName;

    @Schema(
            title = "phoneNumber"
    )
    private String phoneNumber;

    @Schema(
            title = "status"
    )
    private Integer status;

    @Schema(
            title = "role"
    )
    private User.UserRole role;

    @Schema(
            title = "avatarUrl"
    )
    private String avatarUrl;

    @Schema(
            title = "bio"
    )
    private String bio;
}
