/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.comment.service.impl;

import cn.chenyunlong.common.constants.CodeEnum;
import cn.chenyunlong.common.exception.BusinessException;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.jpa.support.EntityOperations;
import cn.chenyunlong.jpa.support.domain.BaseEntity;
import cn.chenyunlong.qing.domain.anime.comment.Comment;
import cn.chenyunlong.qing.domain.anime.comment.creator.CommentCreator;
import cn.chenyunlong.qing.domain.anime.comment.mapper.CommentMapper;
import cn.chenyunlong.qing.domain.anime.comment.query.CommentQuery;
import cn.chenyunlong.qing.domain.anime.comment.repository.CommentRepository;
import cn.chenyunlong.qing.domain.anime.comment.service.ICommentService;
import cn.chenyunlong.qing.domain.anime.comment.updater.CommentUpdater;
import cn.chenyunlong.qing.domain.anime.comment.vo.CommentVO;
import com.querydsl.core.BooleanBuilder;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;
import java.util.stream.Collectors;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class CommentServiceImpl implements ICommentService {
    private final CommentRepository commentRepository;

    /**
     * createImpl
     */
    @Override
    public Long createComment(CommentCreator creator) {
        Optional<Comment> comment = EntityOperations.doCreate(commentRepository)
                .create(() -> CommentMapper.INSTANCE.dtoToEntity(creator))
                .update(Comment::init)
                .execute();
        return comment.isPresent() ? comment.get().getId() : 0;
    }

    /**
     * update
     */
    @Override
    public void updateComment(CommentUpdater updater) {
        EntityOperations.doUpdate(commentRepository)
                .loadById(updater.getId())
                .update(updater::updateComment)
                .execute();
    }

    /**
     * valid
     */
    @Override
    public void validComment(Long id) {
        EntityOperations.doUpdate(commentRepository)
                .loadById(id)
                .update(BaseEntity::valid)
                .execute();
    }

    /**
     * invalid
     */
    @Override
    public void invalidComment(Long id) {
        EntityOperations.doUpdate(commentRepository)
                .loadById(id)
                .update(BaseEntity::invalid)
                .execute();
    }

    /**
     * findById
     */
    @Override
    public CommentVO findById(Long id) {
        Optional<Comment> comment = commentRepository.findById(id);
        return new CommentVO(comment.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
    }

    /**
     * findByPage
     */
    @Override
    public Page<CommentVO> findByPage(PageRequestWrapper<CommentQuery> query) {
        BooleanBuilder booleanBuilder = new BooleanBuilder();
        Page<Comment> page = commentRepository.findAll(booleanBuilder,
                PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                        Sort.Direction.DESC, "createdAt")));
        return new PageImpl<>(page.getContent()
                .stream().map(CommentVO::new)
                .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
    }
}
