// Auto Generated by Qing Code Generator
// Do not modify this file manually
// Generated at: 2025-08-24T17:09:09.939541600
package cn.chenyunlong.codegen.example.domain.dto.creator;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * Order创建请求对象
 *
 * @author Qing Code Generator
 */
@Schema(
        name = "OrderCreator",
        description = "Order创建请求对象"
)
@Data
public class OrderCreator {
    @Schema(
            description = "orderNumber"
    )
    private String orderNumber;

    @Schema(
            description = "amount"
    )
    private Double amount;

    @Schema(
            description = "status"
    )
    private String status;
}
