/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCard: typeof import('@layui/layui-vue')['LayCard']
    LayCascader: typeof import('@layui/layui-vue')['LayCascader']
    LayCheckbox: typeof import('@layui/layui-vue')['LayCheckbox']
    LayCheckboxGroup: typeof import('@layui/layui-vue')['LayCheckboxGroup']
    LayColorPicker: typeof import('@layui/layui-vue')['LayColorPicker']
    LayDatePicker: typeof import('@layui/layui-vue')['LayDatePicker']
    LayException: typeof import('@layui/layui-vue')['LayException']
    LayFooter: typeof import('@layui/layui-vue')['LayFooter']
    LayForm: typeof import('@layui/layui-vue')['LayForm']
    LayFormItem: typeof import('@layui/layui-vue')['LayFormItem']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayIconPicker: typeof import('@layui/layui-vue')['LayIconPicker']
    LayInput: typeof import('@layui/layui-vue')['LayInput']
    LayLayer: typeof import('@layui/layer-vue')['LayLayer']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LayMenu: typeof import('@layui/layui-vue')['LayMenu']
    LayMenuItem: typeof import('@layui/layui-vue')['LayMenuItem']
    LayPage: typeof import('@layui/layui-vue')['LayPage']
    LayRadio: typeof import('@layui/layui-vue')['LayRadio']
    LayRadioButton: typeof import('@layui/layui-vue')['LayRadioButton']
    LayRate: typeof import('@layui/layui-vue')['LayRate']
    LaySelect: typeof import('@layui/layui-vue')['LaySelect']
    LaySelectOption: typeof import('@layui/layui-vue')['LaySelectOption']
    LaySide: typeof import('@layui/layui-vue')['LaySide']
    LaySlider: typeof import('@layui/layui-vue')['LaySlider']
    LaySubMenu: typeof import('@layui/layui-vue')['LaySubMenu']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    LayTable: typeof import('@layui/layui-vue')['LayTable']
    LayTextarea: typeof import('@layui/layui-vue')['LayTextarea']
    LayTreeSelect: typeof import('@layui/layui-vue')['LayTreeSelect']
    LayUpload: typeof import('@layui/layui-vue')['LayUpload']
    MyDPlayer: typeof import('./src/components/MyDPlayer.vue')['default']
    NavItem: typeof import('./src/components/block/Nav-Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selector: typeof import('./src/components/block/Selector.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/block/WelcomeItem.vue')['default']
  }
}
