/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayContainer: typeof import('@layui/layui-vue')['LayContainer']
    LayDropdown: typeof import('@layui/layui-vue')['LayDropdown']
    LayDropdownMenu: typeof import('@layui/layui-vue')['LayDropdownMenu']
    LayDropdownMenuItem: typeof import('@layui/layui-vue')['LayDropdownMenuItem']
    LayFooter: typeof import('@layui/layui-vue')['LayFooter']
    LayForm: typeof import('@layui/layui-vue')['LayForm']
    LayFormItem: typeof import('@layui/layui-vue')['LayFormItem']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayInput: typeof import('@layui/layui-vue')['LayInput']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LaySide: typeof import('@layui/layui-vue')['LaySide']
    LaySpace: typeof import('@layui/layui-vue')['LaySpace']
    MyDPlayer: typeof import('./src/components/MyDPlayer.vue')['default']
    NavItem: typeof import('./src/components/block/Nav-Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selecter: typeof import('./src/components/block/Selecter.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/block/WelcomeItem.vue')['default']
  }
}
