-- 创建角色权限关联表
-- 说明：使用单列主键并对 (role_id, permission_id) 建唯一约束，便于维护
CREATE TABLE IF NOT EXISTS SYS_ROLE_PERMISSION
(
    ID
    BIGSERIAL
    PRIMARY
    KEY,
    ROLE_ID
    BIGINT
    NOT
    NULL,
    PERMISSION_ID
    BIGINT
    NOT
    NULL,
    CREATED_AT
    TIMESTAMP
    DEFAULT
    CURRENT_TIMESTAMP,
    UPDATED_AT
    TIMESTAMP
    DEFAULT
    CURRENT_TIMESTAMP,
    CONSTRAINT
    FK_ROLE_PERMISSION_ROLE
    FOREIGN
    KEY
(
    ROLE_ID
) REFERENCES SYS_ROLE
(
    ID
),
    CONSTRAINT FK_ROLE_PERMISSION_PERMISSION FOREIGN KEY
(
    PERMISSION_ID
) REFERENCES SYS_PERMISSION
(
    ID
),
    CONSTRAINT UK_ROLE_PERMISSION UNIQUE
(
    ROLE_ID,
    PERMISSION_ID
)
    );

-- 触发器用于自动更新 updated_at 时间戳（PostgreSQL示例）
CREATE
OR REPLACE FUNCTION UPDATE_UPDATED_AT_COLUMN(
) RETURNS TRIGGER AS
    $$
BEGIN NEW.UPDATED_AT
= NOW();
RETURN NEW;
END;
$$
LANGUAGE 'plpgsql';
DROP TRIGGER IF EXISTS UPDATE_SYS_ROLE_PERMISSION_UPDATED_AT ON SYS_ROLE_PERMISSION;
CREATE TRIGGER UPDATE_SYS_ROLE_PERMISSION_UPDATED_AT
    BEFORE
        UPDATE
    ON SYS_ROLE_PERMISSION
    FOR EACH ROW EXECUTE PROCEDURE UPDATE_UPDATED_AT_COLUMN(
);
