// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.district.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

import java.lang.String;

import lombok.Data;

@Schema
@Data
public class DistrictCreateRequest implements Request {
    @Schema(
            title = "name",
            description = "name"
    )
    private String name;

    @Schema(
            title = "code",
            description = "code"
    )
    private String code;

    @Schema(
            title = "description",
            description = "description"
    )
    private String description;
}
