# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches:
      - '**'
    paths:
      - ".github/workflows/build.yml"
      - "pom.xml"
      - "qing-bom/**"
      - "qing-commons/**"
      - "qing-starters/**"
      - "qing-domain-common/**"
      - "qing-infrastructure/**"
      - "qing-services/qing-service-anime/**"
      - "qing-services/qing-service-auth/**"
  pull_request:
    branches: [ main ]

# 取消正在运行的工作流，避免资源浪费
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Xmx2048m -XX:MaxMetaspaceSize=512m"
  MAVEN_CLI_OPTS: "--no-transfer-progress --batch-mode --errors --fail-at-end --show-version"

jobs:
  # 检测变更的服务
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      anime-changed: ${{ steps.changes.outputs.anime }}
      auth-changed: ${{ steps.changes.outputs.auth }}
      common-changed: ${{ steps.changes.outputs.common }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            anime:
              - 'qing-services/qing-service-anime/**'
              - 'qing-commons/**'
              - 'qing-domain-common/**'
              - 'qing-infrastructure/**'
              - 'qing-bom/**'
              - 'pom.xml'
            auth:
              - 'qing-services/qing-service-auth/**'
              - 'qing-commons/**'
              - 'qing-domain-common/**'
              - 'qing-infrastructure/**'
              - 'qing-bom/**'
              - 'pom.xml'
            common:
              - 'qing-commons/**'
              - 'qing-domain-common/**'
              - 'qing-infrastructure/**'
              - 'qing-bom/**'
              - 'qing-starters/**'
              - 'pom.xml'

  # 构建公共模块
  build-common:
    needs: detect-changes
    if: needs.detect-changes.outputs.common-changed == 'true'
    timeout-minutes: 8
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 浅克隆节省时间
      
      - name: Set up JDK 21
        uses: useblacksmith/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            .m2/repository
          key: ${{ runner.os }}-maven-common-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-common-
            ${{ runner.os }}-maven-
      
      - name: Build Common Modules
        run: |
          mvn ${{ env.MAVEN_CLI_OPTS }} clean compile \
            -pl qing-commons,qing-domain-common,qing-infrastructure,qing-bom,qing-starters \
            -am -f pom.xml

  # 并行构建服务
  build-services:
    needs: [detect-changes, build-common]
    if: always() && (needs.detect-changes.outputs.anime-changed == 'true' || needs.detect-changes.outputs.auth-changed == 'true')
    timeout-minutes: 12
    runs-on: blacksmith-4vcpu-ubuntu-2404
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: anime
            path: qing-services/qing-service-anime/anime-interfaces
            condition: ${{ needs.detect-changes.outputs.anime-changed == 'true' }}
          - name: auth
            path: qing-services/qing-service-auth/auth-interfaces
            condition: ${{ needs.detect-changes.outputs.auth-changed == 'true' }}
    steps:
      - name: Skip if service unchanged
        if: matrix.service.condition != 'true'
        run: |
          echo "Skipping ${{ matrix.service.name }} service - no changes detected"
          exit 0
      
      - name: Checkout
        if: matrix.service.condition == 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Set up JDK 21
        if: matrix.service.condition == 'true'
        uses: useblacksmith/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Cache Maven dependencies
        if: matrix.service.condition == 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            .m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.service.name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.service.name }}-
            ${{ runner.os }}-maven-common-
            ${{ runner.os }}-maven-
      
      - name: Build ${{ matrix.service.name }} Service
        if: matrix.service.condition == 'true'
        run: |
          mvn ${{ env.MAVEN_CLI_OPTS }} clean package \
            -pl ${{ matrix.service.path }} -am -f pom.xml \
            -DskipTests=false -Dcheckstyle.skip=false
      
      - name: Upload build artifacts
        if: matrix.service.condition == 'true' && success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service.name }}-service-jar
          path: ${{ matrix.service.path }}/target/*.jar
          retention-days: 1
