# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches:
      - '**'
    paths:
      - ".github/workflows/build.yml"
      - "pom.xml"
      - "qing-bom/**"
      - "qing-commons"
      - "qing-starters/**"
      - "qing-domain-common/*"
      - "qing-infrastructure/**"
      - "qing-services/qing-service-anime/**"
      - "qing-services/qing-service-auth/**"
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt-hotspot'
          cache: maven
      - name: Build Anime Service
        run: mvn --no-transfer-progress clean package -pl qing-services/qing-service-anime/anime-interfaces -am -f pom.xml
      - name: Build Auth Service
        run: mvn --no-transfer-progress clean package -pl qing-services/qing-service-auth/auth-interfaces -am -f pom.xml
