// ---Auto Generated by Project Qing ---
package cn.chenyunlong.qing.domain.anime.anime.request;

import cn.chenyunlong.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema
public class AnimeInfoQueryRequest implements Request {
}
