version: '3.8'
services:
  nacos:
    image: qingpan/rnacos:stable
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    environment:
      - RNACOS_INIT_ADMIN_USERNAME=admin
      - RNACOS_INIT_ADMIN_PASSWORD=admin
      - RNACOS_ENABLE_NO_AUTH_CONSOLE=true
      - RNACOS_CONSOLE_ENABLE_CAPTCHA=false
    volumes:
      - /var/nacos/io:/io:rw
    restart: always
