// ---Auto Generated by Qing-Generator --
package cn.chenyunlong.qing.domain.attachement.mapper;

import cn.chenyunlong.qing.domain.attachement.Attachment;
import cn.chenyunlong.qing.domain.attachement.creator.AttachmentCreator;
import cn.chenyunlong.qing.domain.attachement.query.AttachmentQuery;
import cn.chenyunlong.qing.domain.attachement.request.AttachmentCreateRequest;
import cn.chenyunlong.qing.domain.attachement.request.AttachmentQueryRequest;
import cn.chenyunlong.qing.domain.attachement.request.AttachmentUpdateRequest;
import cn.chenyunlong.qing.domain.attachement.response.AttachmentResponse;
import cn.chenyunlong.qing.domain.attachement.updater.AttachmentUpdater;
import cn.chenyunlong.qing.domain.attachement.vo.AttachmentVO;
import cn.hutool.core.bean.BeanUtil;

public interface AttachmentMapper {
    AttachmentMapper INSTANCE = new AttachmentMapper() {};

    default Attachment dtoToEntity(AttachmentCreator dto) {
        return BeanUtil.copyProperties(dto, Attachment.class);
    }

    default AttachmentUpdater request2Updater(AttachmentUpdateRequest request) {
        return BeanUtil.copyProperties(request, AttachmentUpdater.class);
    }

    default AttachmentCreator request2Dto(AttachmentCreateRequest request) {
        return BeanUtil.copyProperties(request, AttachmentCreator.class);
    }

    default AttachmentQuery request2Query(AttachmentQueryRequest request) {
        return BeanUtil.copyProperties(request, AttachmentQuery.class);
    }

    default AttachmentResponse vo2Response(AttachmentVO vo) {
        return BeanUtil.copyProperties(vo, AttachmentResponse.class);
    }

    default AttachmentResponse vo2CustomResponse(AttachmentVO vo) {
        return vo2Response(vo);
    }
}
