// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.anime.playlist.mapper;

import cn.chenyunlong.qing.domain.anime.playlist.Playlist;
import cn.chenyunlong.qing.domain.anime.playlist.creator.PlaylistCreator;
import cn.chenyunlong.qing.domain.anime.playlist.query.PlaylistQuery;
import cn.chenyunlong.qing.domain.anime.playlist.request.PlaylistCreateRequest;
import cn.chenyunlong.qing.domain.anime.playlist.request.PlaylistQueryRequest;
import cn.chenyunlong.qing.domain.anime.playlist.request.PlaylistUpdateRequest;
import cn.chenyunlong.qing.domain.anime.playlist.response.PlaylistResponse;
import cn.chenyunlong.qing.domain.anime.playlist.updater.PlaylistUpdater;
import cn.chenyunlong.qing.domain.anime.playlist.vo.PlaylistVO;
import cn.hutool.core.bean.BeanUtil;

public interface PlaylistMapper {
    PlaylistMapper INSTANCE = new PlaylistMapper() {};

    default Playlist dtoToEntity(PlaylistCreator dto) {
        return BeanUtil.copyProperties(dto, Playlist.class);
    }

    default PlaylistUpdater request2Updater(PlaylistUpdateRequest request) {
        return BeanUtil.copyProperties(request, PlaylistUpdater.class);
    }

    default PlaylistCreator request2Dto(PlaylistCreateRequest request) {
        return BeanUtil.copyProperties(request, PlaylistCreator.class);
    }

    default PlaylistQuery request2Query(PlaylistQueryRequest request) {
        return BeanUtil.copyProperties(request, PlaylistQuery.class);
    }

    default PlaylistResponse vo2Response(PlaylistVO vo) {
        return BeanUtil.copyProperties(vo, PlaylistResponse.class);
    }

    default PlaylistResponse vo2CustomResponse(PlaylistVO vo) {
        return vo2Response(vo);
    }
}
