/*
 * Copyright (c) 2023  YunLong Chen
 * Project Qing is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 *
 */

// ---Auto Generated by Qing-Generator ---
package cn.chenyunlong.qing.domain.system.version.service.impl;

import cn.chenyunlong.common.constants.CodeEnum;
import cn.chenyunlong.common.exception.BusinessException;
import cn.chenyunlong.common.model.PageRequestWrapper;
import cn.chenyunlong.jpa.support.EntityOperations;
import cn.chenyunlong.jpa.support.domain.BaseEntity;
import cn.chenyunlong.qing.domain.system.version.Version;
import cn.chenyunlong.qing.domain.system.version.creator.VersionCreator;
import cn.chenyunlong.qing.domain.system.version.mapper.VersionMapper;
import cn.chenyunlong.qing.domain.system.version.query.VersionQuery;
import cn.chenyunlong.qing.domain.system.version.repository.VersionRepository;
import cn.chenyunlong.qing.domain.system.version.service.IVersionService;
import cn.chenyunlong.qing.domain.system.version.updater.VersionUpdater;
import cn.chenyunlong.qing.domain.system.version.vo.VersionVO;
import com.querydsl.core.BooleanBuilder;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;
import java.util.stream.Collectors;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class VersionServiceImpl implements IVersionService {
    private final VersionRepository versionRepository;

    /**
     * createImpl
     */
    @Override
    public Long createVersion(VersionCreator creator) {
        Optional<Version> version = EntityOperations.doCreate(versionRepository)
                .create(() -> VersionMapper.INSTANCE.dtoToEntity(creator))
                .update(Version::init)
                .execute();
        return version.isPresent() ? version.get().getId() : 0;
    }

    /**
     * update
     */
    @Override
    public void updateVersion(VersionUpdater updater) {
        EntityOperations.doUpdate(versionRepository)
                .loadById(updater.getId())
                .update(updater::updateVersion)
                .execute();
    }

    /**
     * valid
     */
    @Override
    public void validVersion(Long id) {
        EntityOperations.doUpdate(versionRepository)
                .loadById(id)
                .update(BaseEntity::valid)
                .execute();
    }

    /**
     * invalid
     */
    @Override
    public void invalidVersion(Long id) {
        EntityOperations.doUpdate(versionRepository)
                .loadById(id)
                .update(BaseEntity::invalid)
                .execute();
    }

    /**
     * findById
     */
    @Override
    public VersionVO findById(Long id) {
        Optional<Version> version = versionRepository.findById(id);
        return new VersionVO(version.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
    }

    /**
     * findByPage
     */
    @Override
    public Page<VersionVO> findByPage(PageRequestWrapper<VersionQuery> query) {
        BooleanBuilder booleanBuilder = new BooleanBuilder();
        Page<Version> page = versionRepository.findAll(booleanBuilder,
                PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                        Sort.Direction.DESC, "createdAt")));
        return new PageImpl<>(page.getContent()
                .stream().map(VersionVO::new)
                .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
    }
}
